// stars-data.js
// This file contains the `stars` array extracted from
// interactive_northern_southern_star_catalog_25.html
// Fields: name, constellation, visibility, mag, distance, lum, temp, radius, mass, age, spectral, starType, exo (bool), exoCount, notes
const stars = [
  {
    name: "Sirius",
    constellation: "Canis Major",
    visibility: "Both",
    mag: -1.46,
    distance: 8.6,
    lum: 25,
    temp: 9940,
    radius: 1.7,
    mass: 2.0,
    age: 0.25,
    spectral: "A1 V",
    numStars: 2,
    starType: "Main sequence",
    exo: false,
    exoCount: 0,
    notes: "Brightest night star; binary with white dwarf Sirius B.",
  },
  {
    name: "Canopus",
    constellation: "Carina",
    visibility: "Southern",
    mag: -0.72,
    distance: 310,
    lum: 10000,
    temp: 7350,
    radius: 71,
    mass: 8.0,
    age: 0.03,
    spectral: "F0 Ib",
    starType: "Supergiant",
    exo: false,
    exoCount: 0,
    notes: "Second brightest star.",
  },
  {
    name: "Arcturus",
    constellation: "Boötes",
    visibility: "Northern",
    mag: -0.05,
    distance: 36.7,
    lum: 170,
    temp: 4290,
    radius: 25,
    mass: 1.1,
    age: 7.0,
    spectral: "K1.5 III",
    starType: "Red giant",
    exo: false,
    exoCount: 0,
    notes: "Orange giant; very old population.",
  },
  {
    name: "Alpha Centauri",
    constellation: "Centaurus",
    visibility: "Southern",
    mag: -0.27,
    distance: 4.37,
    lum: 1.5,
    temp: 5790,
    radius: 1.2,
    mass: 1.1,
    age: 5.5,
    spectral: "G2 V",
    numStars: 3,
    starType: "Main sequence",
    exo: true,
    exoCount: 1,
    notes: "Part of Alpha Centauri system (Proxima b confirmed).",
  },
  {
    name: "Vega",
    constellation: "Lyra",
    visibility: "Northern",
    mag: 0.03,
    distance: 25.0,
    lum: 40,
    temp: 9600,
    radius: 2.4,
    mass: 2.1,
    age: 0.45,
    spectral: "A0 V",
    starType: "Main sequence",
    exo: false,
    exoCount: 0,
    notes: "Debris disk; fast rotator.",
  },
  {
    name: "Capella (A/B)",
    constellation: "Auriga",
    visibility: "Northern",
    mag: 0.08,
    distance: 42.8,
    lum: 78,
    temp: 4900,
    radius: 12,
    mass: 2.5,
    age: 0.6,
    spectral: "G8 III + G0 III",
    numStars: 4,
    starType: "Yellow giant binary",
    exo: false,
    exoCount: 0,
    notes: "Close pair of yellow giants.",
  },
  {
    name: "Rigel",
    constellation: "Orion",
    visibility: "Both",
    mag: 0.12,
    distance: 860,
    lum: 120000,
    temp: 12000,
    radius: 78,
    mass: 21,
    age: 0.008,
    spectral: "B8 Ia",
    numStars: 4,
    starType: "Blue supergiant",
    uncertainty: [1, 2], // 1=distance/parallax disagreement, 2=multiplicity disputed
    sources: ["https://en.wikipedia.org/wiki/Rigel"],
    exo: false,
    exoCount: 0,
    notes: "Extremely luminous; short-lived.",
  },
  {
    name: "Procyon",
    constellation: "Canis Minor",
    visibility: "Northern",
    mag: 0.38,
    distance: 11.4,
    lum: 7,
    temp: 6530,
    radius: 2.0,
    mass: 1.5,
    age: 1.7,
    spectral: "F5 IV–V",
    numStars: 2,
    starType: "Subgiant",
    exo: false,
    exoCount: 0,
    notes: "White dwarf companion (Procyon B).",
  },
  {
    name: "Achernar",
    constellation: "Eridanus",
    visibility: "Southern",
    mag: 0.46,
    distance: 139,
    lum: 3150,
    temp: 15000,
    radius: 9,
    mass: 6.7,
    age: 0.04,
    spectral: "B6 Vep",
    numStars: 2,
    starType: "Main sequence",
    exo: false,
    exoCount: 0,
    notes: "Rapid rotator; oblate.",
  },
  {
    name: "Betelgeuse",
    constellation: "Orion",
    visibility: "Both",
    mag: 0.5,
    distance: 640,
    lum: 100000,
    temp: 3500,
    radius: 950,
    mass: 20,
    age: 0.01,
    spectral: "M1–2 Iab",
    starType: "Red supergiant",
    uncertainty: [1, 4], // distance uncertain; physical parameter variance
    sources: ["https://en.wikipedia.org/wiki/Betelgeuse"],
    exo: false,
    exoCount: 0,
    notes: "Semiregular variable; pre-supernova.",
  },
  {
    name: "Hadar (Beta Centauri)",
    constellation: "Centaurus",
    visibility: "Southern",
    mag: 0.61,
    distance: 390,
    lum: 50000,
    temp: 25000,
    radius: 8,
    mass: 10,
    age: 0.014,
    spectral: "B1 III",
    /* Beta Centauri has multiple confirmed components; sources list multiple
       spectroscopic/visual components. Set to 4 based on cataloged components. */
    numStars: 4,
    starType: "Blue giant",
    exo: false,
    exoCount: 0,
    notes: "Massive triple system.",
  },
  {
    name: "Altair",
    constellation: "Aquila",
    visibility: "Northern",
    mag: 0.77,
    distance: 16.7,
    lum: 11,
    temp: 7755,
    radius: 1.8,
    mass: 1.8,
    age: 1.2,
    spectral: "A7 V",
    starType: "Main sequence",
    exo: false,
    exoCount: 0,
    notes: "Rapid spin; equatorial bulge.",
  },
  {
    name: "Acrux (Alpha Crucis)",
    constellation: "Crux",
    visibility: "Southern",
    mag: 0.77,
    distance: 320,
    lum: 25000,
    temp: 28000,
    radius: 9,
    mass: 14,
    age: 0.01,
    spectral: "B0.5 IV",
    numStars: 6,
    starType: "Blue subgiant",
    // Per-component spectral types (α Cru system has multiple components).
    // These follow the order shown in literature: Aa, Ab, A2, C a/b, D (approx).
    // Values are illustrative and used to color/size the legend dots for the system.
    components: ["B0.5 IV", "B7?V", "B1 Vn", "B4 V", "G?V", "M0 V"],
    exo: false,
    exoCount: 0,
    notes: "Brightest in Southern Cross.",
  },
  {
    name: "Aldebaran",
    constellation: "Taurus",
    visibility: "Northern",
    mag: 0.85,
    distance: 65.0,
    lum: 440,
    temp: 3900,
    radius: 44,
    mass: 1.2,
    age: 6.6,
    spectral: "K5 III",
    numStars: 2,
    starType: "Red giant",
    exo: false,
    exoCount: 0,
    notes: "Orange giant; planet claim unconfirmed.",
  },
  {
    name: "Spica",
    constellation: "Virgo",
    visibility: "Both",
    mag: 0.98,
    distance: 250,
    lum: 12100,
    temp: 22400,
    radius: 7.5,
    mass: 11,
    age: 0.013,
    spectral: "B1 V + B2 V",
    numStars: 2,
    starType: "Spectroscopic binary",
    exo: false,
    exoCount: 0,
    notes: "Massive close pair.",
  },
  {
    name: "Antares",
    constellation: "Scorpius",
    visibility: "Southern",
    mag: 1.06,
    distance: 550,
    lum: 75000,
    temp: 3600,
    radius: 680,
    mass: 18,
    age: 0.012,
    spectral: "M1 Ib",
    numStars: 2,
    starType: "Red supergiant",
    exo: false,
    exoCount: 0,
    notes: "Rival of Mars; huge and cool.",
  },
  {
    name: "Pollux",
    constellation: "Gemini",
    visibility: "Northern",
    mag: 1.14,
    distance: 34,
    lum: 43,
    temp: 4865,
    radius: 8.8,
    mass: 1.9,
    age: 0.7,
    spectral: "K0 III",
    starType: "Orange giant",
    exo: true,
    exoCount: 1,
    notes: "Confirmed exoplanet Pollux b (gas giant).",
  },
  {
    name: "Fomalhaut",
    constellation: "Piscis Austrinus",
    visibility: "Southern",
    mag: 1.16,
    distance: 25,
    lum: 16,
    temp: 8590,
    radius: 1.8,
    mass: 1.9,
    age: 0.44,
    spectral: "A3 V",
    numStars: 3,
    starType: "Main sequence",
    exo: true,
    exoCount: 1,
    notes: "Famous debris ring; planet candidate reported.",
  },
  {
    name: "Deneb",
    constellation: "Cygnus",
    visibility: "Northern",
    mag: 1.25,
    distance: 2600,
    lum: 200000,
    temp: 8525,
    radius: 200,
    mass: 19,
    age: 0.006,
    spectral: "A2 Ia",
    starType: "White supergiant",
    uncertainty: [1, 3], // 1=distance/parallax disagreement, 3=spectral/luminosity disagreement
    sources: ["https://en.wikipedia.org/wiki/Deneb"],
    exo: false,
    exoCount: 0,
    notes: "One of the most luminous visible stars.",
  },
  {
    name: "Mimosa (Beta Crucis)",
    constellation: "Crux",
    visibility: "Southern",
    mag: 1.25,
    distance: 280,
    lum: 34000,
    temp: 27000,
    radius: 8.4,
    mass: 14,
    age: 0.008,
    spectral: "B0.5 III",
    starType: "Blue giant",
    exo: false,
    exoCount: 0,
    notes: "Bright Southern Cross member.",
  },
  {
    name: "Regulus",
    constellation: "Leo",
    visibility: "Northern",
    mag: 1.35,
    distance: 79,
    lum: 350,
    temp: 12100,
    radius: 3.1,
    mass: 3.8,
    age: 0.15,
    spectral: "B7 V",
    starType: "Main sequence",
    exo: false,
    exoCount: 0,
    notes: "Rapidly spinning, oblate star.",
  },
  {
    name: "Adhara (Epsilon CMa)",
    constellation: "Canis Major",
    visibility: "Both",
    mag: 1.5,
    distance: 430,
    lum: 38000,
    temp: 22200,
    radius: 14,
    mass: 12,
    age: 0.022,
    spectral: "B2 II",
    numStars: 2,
    starType: "Blue giant",
    exo: false,
    exoCount: 0,
    notes: "Was much brighter a few Myr ago.",
  },
  {
    name: "Shaula (Lambda Sco)",
    constellation: "Scorpius",
    visibility: "Southern",
    mag: 1.62,
    distance: 570,
    lum: 35000,
    temp: 22000,
    radius: 8,
    mass: 11,
    age: 0.01,
    spectral: "B2 IV",
    numStars: 3,
    starType: "Blue subgiant",
    exo: false,
    exoCount: 0,
    notes: "Multiple hot system.",
  },
  {
    name: "Castor",
    constellation: "Gemini",
    visibility: "Northern",
    mag: 1.58,
    distance: 52,
    lum: 37,
    temp: 8840,
    radius: 2.4,
    mass: 2.0,
    age: 0.37,
    spectral: "A1 V",
    numStars: 6,
    starType: "Multiple (sextuple)",
    // Per-component spectral types for Castor (Aa+Ab, Ba+Bb, Ca+Cb = YY Gem).
    // According to literature/Wikipedia the bright primaries are A-type (A1V, Am)
    // and the companions are red dwarfs (dM1e); use those for accurate coloring.
    components: ["A1 V", "dM1e", "Am", "dM1e", "dM1e", "dM1e"],
    exo: false,
    exoCount: 0,
    notes: "Complex six-star system.",
  },
  {
    name: "Gacrux (Gamma Cru)",
    constellation: "Crux",
    visibility: "Southern",
    mag: 1.63,
    distance: 88,
    lum: 820,
    temp: 3620,
    radius: 84,
    mass: 1.5,
    age: 0.1,
    spectral: "M3 III",
    starType: "Red giant",
    exo: false,
    exoCount: 0,
    notes: "Top of Southern Cross.",
  },
  // --- Additional bright stars (to make 50 total) ---
  {
    name: "Bellatrix",
    constellation: "Orion",
    visibility: "Both",
    mag: 1.64,
    distance: 244,
    lum: 900,
    temp: 22000,
    radius: 5.8,
    mass: 8.6,
    age: 0.02,
    spectral: "B2 III",
    starType: "Blue giant",
    exo: false,
    exoCount: 0,
    notes: "Left shoulder of Orion.",
  },
  {
    name: "Elnath",
    constellation: "Taurus",
    visibility: "Northern",
    mag: 1.65,
    distance: 131,
    lum: 700,
    temp: 13000,
    radius: 4.0,
    mass: 6.9,
    age: 0.03,
    spectral: "B7 III",
    starType: "Blue giant",
    exo: false,
    exoCount: 0,
    notes: "Beta Tauri, on Taurus horn.",
  },
  {
    name: "Alnilam",
    constellation: "Orion",
    visibility: "Both",
    mag: 1.69,
    distance: 1340,
    lum: 275000,
    temp: 27500,
    radius: 24,
    mass: 40,
    age: 0.005,
    spectral: "B0 Ia",
    numStars: 3,
    starType: "Blue supergiant",
    uncertainty: [1], // distance/parallax disagreement in literature
    sources: ["https://en.wikipedia.org/wiki/Alnilam"],
    exo: false,
    exoCount: 0,
    notes: "Middle star of Orion's Belt.",
  },
  {
    name: "Alnitak",
    constellation: "Orion",
    visibility: "Both",
    mag: 1.74,
    distance: 820,
    lum: 100000,
    temp: 30000,
    radius: 20,
    mass: 30,
    age: 0.006,
    spectral: "O9.7 Ib",
    numStars: 3,
    starType: "Blue supergiant",
    uncertainty: [1, 2], // distance disagreement; multiple components
    sources: ["https://en.wikipedia.org/wiki/Alnitak"],
    exo: false,
    exoCount: 0,
    notes: "Left-most of Orion's Belt.",
  },
  {
    name: "Mintaka",
    constellation: "Orion",
    visibility: "Both",
    mag: 2.23,
    distance: 915,
    lum: 90000,
    temp: 31000,
    radius: 18,
    mass: 30,
    age: 0.006,
    spectral: "O9.5 II",
    numStars: 3,
    starType: "Blue giant",
    uncertainty: [1], // Hipparcos vs cluster/Gaia distance discrepancies
    sources: ["https://en.wikipedia.org/wiki/Mintaka"],
    exo: false,
    exoCount: 0,
    notes: "Right-most of Orion's Belt.",
  },
  {
    name: "Saiph",
    constellation: "Orion",
    visibility: "Both",
    mag: 2.06,
    distance: 720,
    lum: 85000,
    temp: 26000,
    radius: 22,
    mass: 25,
    age: 0.007,
    spectral: "B0.5 Ia",
    starType: "Supergiant",
    numStars: 1,
    uncertainty: [1], // distance estimate varies between sources
    sources: ["https://en.wikipedia.org/wiki/Saiph"],
    exo: false,
    exoCount: 0,
    notes: "Knee of Orion.",
  },
  {
    name: "Alkaid",
    constellation: "Ursa Major",
    visibility: "Northern",
    mag: 1.86,
    distance: 101,
    lum: 300,
    temp: 20000,
    radius: 3.6,
    mass: 6.0,
    age: 0.1,
    spectral: "B3 V",
    starType: "Main sequence",
    exo: false,
    exoCount: 0,
    notes: "End of the Big Dipper's handle.",
  },
  {
    name: "Mizar",
    constellation: "Ursa Major",
    visibility: "Northern",
    mag: 2.23,
    distance: 78,
    lum: 50,
    temp: 9000,
    radius: 3.0,
    mass: 3.5,
    age: 0.4,
    spectral: "A2 V",
    numStars: 4,
    starType: "Multiple (quadruple)",
    exo: false,
    exoCount: 0,
    notes: "Part of the Big Dipper; multiple system.",
  },
  {
    name: "Alioth",
    constellation: "Ursa Major",
    visibility: "Northern",
    mag: 1.76,
    distance: 82,
    lum: 102,
    temp: 9500,
    radius: 3.2,
    mass: 3.0,
    age: 0.3,
    spectral: "A0p",
    starType: "Main sequence",
    exo: false,
    exoCount: 0,
    notes: "Brightest of the Plough's handle stars.",
  },
  {
    name: "Dubhe",
    constellation: "Ursa Major",
    visibility: "Northern",
    mag: 1.79,
    distance: 124,
    lum: 360,
    temp: 9000,
    radius: 25,
    mass: 4.25,
    age: 0.1,
    spectral: "K0 III",
    numStars: 4,
    starType: "Giant",
    exo: false,
    exoCount: 0,
    notes: "One of the pointer stars to Polaris.",
  },
  {
    name: "Merak",
    constellation: "Ursa Major",
    visibility: "Northern",
    mag: 2.37,
    distance: 79,
    lum: 70,
    temp: 9000,
    radius: 3.0,
    mass: 3.0,
    age: 0.4,
    spectral: "A1 V",
    starType: "Main sequence",
    exo: false,
    exoCount: 0,
    notes: "Pointer star in the Big Dipper.",
  },
  {
    name: "Phecda",
    constellation: "Ursa Major",
    visibility: "Northern",
    mag: 2.44,
    distance: 83,
    lum: 60,
    temp: 9000,
    radius: 2.6,
    mass: 2.5,
    age: 0.5,
    spectral: "A0 V",
    starType: "Main sequence",
    exo: false,
    exoCount: 0,
    notes: "Part of the Plough bowl.",
  },
  {
    name: "Polaris",
    constellation: "Ursa Minor",
    visibility: "Northern",
    mag: 1.98,
    distance: 433,
    lum: 2500,
    temp: 6015,
    radius: 46,
    mass: 5.4,
    age: 0.07,
    spectral: "F7 Ib",
    numStars: 3,
    starType: "Cepheid/supergiant",
    exo: false,
    exoCount: 0,
    notes: "North Star; Cepheid variable.",
  },
  {
    name: "Denebola",
    constellation: "Leo",
    visibility: "Northern",
    mag: 2.14,
    distance: 36,
    lum: 15,
    temp: 8500,
    radius: 1.7,
    mass: 1.8,
    age: 0.5,
    spectral: "A3 V",
    starType: "Main sequence",
    exo: false,
    exoCount: 0,
    notes: "Tail of Leo.",
  },
  {
    name: "Mirfak",
    constellation: "Perseus",
    visibility: "Northern",
    mag: 1.79,
    distance: 590,
    lum: 4000,
    temp: 8000,
    radius: 30,
    mass: 12,
    age: 0.02,
    spectral: "F5 Ib",
    starType: "Supergiant",
    uncertainty: [1], // file distance differs from common literature value (~510 ly)
    sources: ["https://en.wikipedia.org/wiki/Alpha_Persei"],
    exo: false,
    exoCount: 0,
    notes: "Alpha Persei cluster member.",
  },
  {
    name: "Kaus Australis",
    constellation: "Sagittarius",
    visibility: "Southern",
    mag: 1.79,
    distance: 82,
    lum: 120,
    temp: 12000,
    radius: 4.5,
    mass: 5.5,
    age: 0.1,
    spectral: "B9 II",
    starType: "Bright giant",
    uncertainty: [1], // distance in file differs from some catalog values
    sources: ["https://en.wikipedia.org/wiki/Kaus_Australis"],
    exo: false,
    exoCount: 0,
    notes: "Brightest in Sagittarius.",
  },
  {
    name: "Kaus Borealis",
    constellation: "Sagittarius",
    visibility: "Southern",
    mag: 2.82,
    distance: 140,
    lum: 120,
    temp: 11500,
    radius: 4.3,
    mass: 5.0,
    age: 0.12,
    spectral: "B8 III",
    starType: "Blue giant",
    exo: false,
    exoCount: 0,
    notes: "Part of the Teapot asterism.",
  },
  {
    name: "Avior",
    constellation: "Carina",
    visibility: "Southern",
    mag: 1.86,
    distance: 630,
    lum: 9000,
    temp: 20000,
    radius: 12,
    mass: 15,
    age: 0.01,
    spectral: "B2 IV",
    starType: "Blue subgiant",
    exo: false,
    exoCount: 0,
    notes: "Bright southern star near Canopus.",
  },
  {
    name: "Miaplacidus",
    constellation: "Carina",
    visibility: "Southern",
    mag: 1.67,
    distance: 111,
    lum: 400,
    temp: 8500,
    radius: 3.5,
    mass: 3.2,
    age: 0.3,
    spectral: "A2 II",
    starType: "Bright giant",
    exo: false,
    exoCount: 0,
    notes: "Second-brightest in Carina region.",
  },
  {
    name: "Menkent",
    constellation: "Centaurus",
    visibility: "Southern",
    mag: 2.06,
    distance: 60,
    lum: 160,
    temp: 5600,
    radius: 12,
    mass: 2.8,
    age: 0.25,
    spectral: "K0 III",
    starType: "Giant",
    exo: false,
    exoCount: 0,
    notes: "Theta Centauri.",
  },
  {
    name: "Alpheratz",
    constellation: "Andromeda",
    visibility: "Northern",
    mag: 2.06,
    distance: 97,
    lum: 400,
    temp: 9000,
    radius: 3.2,
    mass: 3.4,
    age: 0.3,
    spectral: "B8 IV",
    starType: "Subgiant",
    exo: false,
    exoCount: 0,
    notes: "Part of the Great Square of Pegasus.",
  },
  {
    name: "Algol",
    constellation: "Perseus",
    visibility: "Northern",
    mag: 2.12,
    distance: 93,
    lum: 150,
    temp: 13000,
    radius: 3.0,
    mass: 3.6,
    age: 0.5,
    spectral: "B8 V",
    numStars: 3,
    starType: "Eclipsing binary (triple)",
    exo: false,
    exoCount: 0,
    notes: "Famous eclipsing binary (Beta Persei).",
  },
  {
    name: "Schedar",
    constellation: "Cassiopeia",
    visibility: "Northern",
    mag: 2.24,
    distance: 230,
    lum: 1200,
    temp: 4750,
    radius: 35,
    mass: 5.0,
    age: 0.08,
    spectral: "K0 III",
    starType: "Giant",
    exo: false,
    exoCount: 0,
    notes: "Alpha Cassiopeiae.",
  },
  {
    name: "Caph",
    constellation: "Cassiopeia",
    visibility: "Northern",
    mag: 2.27,
    distance: 54,
    lum: 80,
    temp: 6000,
    radius: 4.0,
    mass: 2.0,
    age: 0.7,
    spectral: "F2 III",
    starType: "Giant/subgiant",
    exo: false,
    exoCount: 0,
    notes: "Part of the W of Cassiopeia.",
  },
];

// Expose `stars` globally (already global via const); kept for clarity.
// If you prefer a module pattern, we can switch to exporting the array and
// update the HTML to load as a module (<script type="module">).
