// stars-data.js
// This file contains the `stars` array extracted from
// interactive_northern_southern_star_catalog_25.html
// Fields: name, constellation, visibility, mag, distance, lum, temp, radius, mass, age, spectral, starType, exo (bool), exoCount, notes
const stars = [
  {
    name: "Sun (Sol)",
    constellation: "N/A",
    visibility: "Both",
    mag: -26.74,
    distance: 0.0000158,
    lum: 1.0,
    temp: 5778,
    radius: 1.0,
    mass: 1.0,
    age: 4.6,
    spectral: "G2 V",
    starType: "Main sequence",
    exo: false,
    exoCount: 0,
    sources: [
      "https://en.wikipedia.org/wiki/Sun",
      "http://simbad.u-strasbg.fr/simbad/sim-id?Ident=Sun",
    ],
    notes:
      "The Sun (Sol) — our star; closest star to Earth at 1 AU (0.0000158 ly or 8 light-minutes). G2 V yellow dwarf on main sequence, fusing hydrogen into helium in core. Age 4.6 Gyr; will become red giant in ~5 Gyr. Reference star: all stellar parameters (L☉, M☉, R☉, T☉) defined relative to Sun.",
  },
  {
    name: "Sirius",
    constellation: "Canis Major",
    visibility: "Both",
    mag: -1.46,
    distance: 8.6,
    lum: 25,
    temp: 9940,
    radius: 1.7,
    mass: 2.0,
    age: 0.25,
    spectral: "A1 V",
    numStars: 2,
    starType: "Main sequence",
    exo: false,
    exoCount: 0,
    // Sirius is a well-studied binary: bright main-sequence Sirius A and
    // the white-dwarf companion Sirius B. Keep numeric fields unchanged
    // and add conservative per-component rendering + provenance.
    components: [
      { name: "A", spec: "A1 V", visualSize: 38 },
      { name: "B", spec: "DA2 (white dwarf)", visualSize: 12 },
    ],
    sources: [
      "https://en.wikipedia.org/wiki/Sirius",
      "http://simbad.u-strasbg.fr/simbad/sim-id?Ident=Sirius",
    ],
    notes:
      "Binary system: Sirius A (A1 V) + Sirius B (white dwarf). Some historical claims of additional faint companions remain unconfirmed; see sources.",
  },
  {
    name: "Canopus",
    constellation: "Carina",
    visibility: "Southern",
    mag: -0.72,
    distance: 310,
    lum: 10000,
    temp: 7350,
    radius: 71,
    mass: 8.0,
    age: 0.03,
    spectral: "F0 Ib",
    starType: "Supergiant",
    exo: false,
    exoCount: 0,
    // Canopus is generally treated as a single bright F-type supergiant.
    // No well-established close stellar companions; a candidate wide
    // common-proper-motion M-dwarf was reported (Mamajek 2014) at very
    // large projected separation and is not considered a bound close
    // companion. Keep numeric parameters unchanged and add provenance.
    sources: [
      "https://en.wikipedia.org/wiki/Canopus",
      "http://simbad.u-strasbg.fr/simbad/sim-id?Ident=Canopus",
    ],
    notes:
      "Bright F-type supergiant (Canopus). No confirmed close stellar companion; a candidate wide common-proper-motion M-dwarf has been reported but is at very large projected separation (see sources).",
  },
  {
    name: "Arcturus",
    constellation: "Boötes",
    visibility: "Northern",
    mag: -0.05,
    distance: 36.7,
    lum: 170,
    temp: 4290,
    radius: 25,
    mass: 1.1,
    age: 7.0,
    spectral: "K1.5 III",
    starType: "Red giant",
    exo: false,
    exoCount: 0,
    // Arcturus is commonly listed as a single K-type red giant, but a
    // marginal Hipparcos astrometric detection and some radial-velocity
    // studies have suggested a possible low-mass companion; results are
    // inconclusive. We'll flag multiplicity as disputed (conservative)
    // and add provenance rather than declaring a firm companion.
    uncertainty: [2],
    sources: [
      "https://en.wikipedia.org/wiki/Arcturus",
      "http://simbad.u-strasbg.fr/simbad/sim-id?Ident=Arcturus",
    ],
    notes:
      "Bright K1.5 III red giant. Hipparcos astrometry gave a marginal companion detection and some radial-velocity studies have reported long-period signals; multiplicity remains inconclusive — see sources.",
  },
  {
    name: "Alpha Centauri",
    constellation: "Centaurus",
    visibility: "Southern",
    mag: -0.27,
    distance: 4.37,
    lum: 1.5,
    temp: 5790,
    radius: 1.2,
    mass: 1.1,
    age: 5.5,
    spectral: "G2 V",
    numStars: 3,
    starType: "Main sequence",
    // Represent Alpha Centauri as a triple: the close binary AB (A: G2 V, B: K1 V)
    // plus the distant but bound Proxima Centauri (C, a red dwarf). The UI will
    // render one dot per component using the `components` array. We keep numeric
    // astrophysical values unchanged and only add provenance + notes about
    // Proxima's planets so the dataset remains conservative.
    components: [
      { name: "A", spec: "G2 V", visualSize: 36 },
      { name: "B", spec: "K1 V", visualSize: 30 },
      { name: "C (Proxima)", spec: "M5–M6 V", visualSize: 12 },
    ],
    exo: true,
    exoCount: 1,
    sources: [
      "https://en.wikipedia.org/wiki/Alpha_Centauri",
      "http://simbad.u-strasbg.fr/simbad/sim-id?Ident=alpha+centauri",
    ],
    notes:
      "Triple system: Alpha Centauri A (G2 V) + B (K1 V) form the close binary AB; Proxima Centauri (α Cen C, M5–M6 V) is a distant, gravitationally bound red dwarf (Kervella et al. 2017). Proxima hosts confirmed planets (Proxima b and Proxima d); other candidate planets around A/B remain unconfirmed. See sources for details.",
  },
  {
    name: "Vega",
    constellation: "Lyra",
    visibility: "Northern",
    mag: 0.03,
    distance: 25.0,
    lum: 40,
    temp: 9600,
    radius: 2.4,
    mass: 2.1,
    age: 0.45,
    spectral: "A0 V",
    starType: "Main sequence",
    exo: false,
    exoCount: 0,
    // Vega: bright A0V star with a well-studied debris disk and no
    // confirmed planets. There are tentative planet/period signals in
    // the literature (e.g., a 2.43-day candidate signal) but these are
    // unconfirmed; flag as tentative and add provenance.
    sources: [
      "https://en.wikipedia.org/wiki/Vega",
      "http://simbad.u-strasbg.fr/simbad/sim-id?Ident=Vega",
    ],
    uncertainty: [5],
    notes:
      "A0 V main-sequence star with a debris disk. Rapid rotator seen nearly pole-on. No confirmed planets; some tentative planet signals have been reported but remain unconfirmed (see sources). JWST observations show the disk to be exceptionally smooth (2024–2025 results).",
  },
  {
    name: "Capella",
    constellation: "Auriga",
    visibility: "Northern",
    mag: 0.08,
    distance: 42.8,
    lum: 78,
    temp: 4900,
    radius: 12,
    mass: 2.5,
    age: 0.6,
    spectral: "G8 III + G0 III",
    numStars: 4,
    starType: "Yellow giant binary",
    // Per-component objects for Capella (Aa+Ab are the bright G-type giants;
    // the other two are fainter companions). These are illustrative so the
    // UI can render four colored dots matching the system (two large yellow
    // giants and two smaller red/orange companions).
    components: [
      { name: "Aa", spec: "G8 III", visualSize: 36 },
      { name: "Ab", spec: "G0 III", visualSize: 32 },
      { name: "Ba", spec: "M0 V", visualSize: 12 },
      { name: "Bb", spec: "M2 V", visualSize: 12 },
    ],
    exo: false,
    exoCount: 0,
    notes: "Close pair of yellow giants.",
  },
  {
    name: "Rigel",
    constellation: "Orion",
    visibility: "Both",
    mag: 0.12,
    distance: 860,
    lum: 120000,
    temp: 12000,
    radius: 78,
    mass: 21,
    age: 0.008,
    spectral: "B8 Ia",
    numStars: 4,
    starType: "Blue supergiant",
    uncertainty: [1, 2], // 1=distance/parallax disagreement, 2=multiplicity disputed
    sources: ["https://en.wikipedia.org/wiki/Rigel"],
    // Per-component breakdown based on cataloged system: primary Rigel A (B8 Ia)
    // and a nearby BC triple composed of hot B-type main-sequence stars
    // (Ba, Bb spectroscopic pair; C close visual). Represent as four
    // components (A, Ba, Bb, C) so the UI can render one large blue supergiant
    // and three smaller blue/white companions.
    components: [
      { name: "A", spec: "B8 Ia", visualSize: 44 },
      { name: "Ba", spec: "B9 V", visualSize: 18 },
      { name: "Bb", spec: "B9 V", visualSize: 16 },
      { name: "C", spec: "B9 V", visualSize: 16 },
    ],
    exo: false,
    exoCount: 0,
    notes: "Extremely luminous; short-lived.",
  },
  {
    name: "Procyon",
    constellation: "Canis Minor",
    visibility: "Northern",
    mag: 0.38,
    distance: 11.4,
    lum: 7,
    temp: 6530,
    radius: 2.0,
    mass: 1.5,
    age: 1.7,
    spectral: "F5 IV–V",
    numStars: 2,
    starType: "Subgiant",
    exo: false,
    exoCount: 0,
    // Procyon is a nearby binary: Procyon A (F5 IV–V) + Procyon B (white dwarf).
    components: [
      { name: "A", spec: "F5 IV–V", visualSize: 34 },
      { name: "B", spec: "DQZ (white dwarf)", visualSize: 12 },
    ],
    sources: [
      "https://en.wikipedia.org/wiki/Procyon",
      "http://simbad.u-strasbg.fr/simbad/sim-id?Ident=Procyon",
    ],
    notes:
      "Binary system: Procyon A (F5 IV–V) and a faint white-dwarf companion Procyon B (DQZ). Orbital elements and white-dwarf parameters are well-studied (see sources).",
  },
  {
    name: "Achernar",
    constellation: "Eridanus",
    visibility: "Southern",
    mag: 0.46,
    distance: 139,
    lum: 3150,
    temp: 15000,
    radius: 9,
    mass: 6.7,
    age: 0.04,
    spectral: "B6 Vep",
    numStars: 2,
    starType: "Main sequence",
    exo: false,
    exoCount: 0,
    // Achernar is a binary: the rapid-rotating Be primary (A, B6 Vep)
    // and a close A-type companion (B, A0–A3 V). Add per-component
    // entries for rendering and provenance; numeric fields unchanged.
    components: [
      { name: "A", spec: "B6 Vep", visualSize: 40 },
      { name: "B", spec: "A1–A3 V", visualSize: 18 },
    ],
    sources: [
      "https://en.wikipedia.org/wiki/Achernar",
      "http://simbad.u-strasbg.fr/simbad/sim-id?Ident=Achernar",
    ],
    notes:
      "Rapid rotator; oblate. Binary system (A + close A-type companion B) — see sources.",
  },
  {
    name: "Betelgeuse",
    constellation: "Orion",
    visibility: "Both",
    mag: 0.5,
    distance: 640,
    lum: 100000,
    temp: 3500,
    radius: 950,
    mass: 20,
    age: 0.01,
    spectral: "M1–2 Iab",
    starType: "Red supergiant",
    uncertainty: [1, 4], // distance uncertain; physical parameter variance
    sources: ["https://en.wikipedia.org/wiki/Betelgeuse"],
    exo: false,
    exoCount: 0,
    notes: "Semiregular variable; pre-supernova.",
  },
  {
    name: "Hadar (Beta Centauri)",
    constellation: "Centaurus",
    visibility: "Southern",
    mag: 0.61,
    distance: 361,
    lum: 50000,
    temp: 25000,
    radius: 8,
    mass: 10,
    age: 0.014,
    spectral: "B1 III",
    /* Beta Centauri is a triple system: the close spectroscopic pair
       β Cen Aa + Ab (both ~B1 III) and a wider visual companion β Cen B
       (spectral type commonly listed as ~B1 V). Use a 3-component
       `components` array so the UI renders three dots for Hadar. */
    numStars: 3,
    starType: "Blue giant (triple)",
    sources: [
      "https://en.wikipedia.org/wiki/Beta_Centauri",
      "http://simbad.u-strasbg.fr/simbad/sim-id?Ident=Beta+Centauri",
    ],
    components: [
      { name: "Aa", spec: "B1 III", visualSize: 18 },
      { name: "Ab", spec: "B1 III", visualSize: 16 },
      { name: "B", spec: "B1 V", visualSize: 14 },
    ],
    exo: false,
    exoCount: 0,
    notes:
      "Triple system: Aa+Ab (spectroscopic B1 III pair) + B (visual, B1 V). Sources: Wikipedia, SIMBAD.",
  },
  {
    name: "Altair",
    constellation: "Aquila",
    visibility: "Northern",
    mag: 0.77,
    distance: 16.7,
    lum: 11,
    temp: 7755,
    radius: 1.8,
    mass: 1.8,
    age: 1.2,
    spectral: "A7 V",
    starType: "Main sequence",
    exo: false,
    exoCount: 0,
    notes: "Rapid spin; equatorial bulge.",
  },
  {
    name: "Acrux (Alpha Crucis)",
    constellation: "Crux",
    visibility: "Southern",
    mag: 0.77,
    distance: 320,
    lum: 25000,
    temp: 28000,
    radius: 9,
    mass: 14,
    age: 0.01,
    spectral: "B0.5 IV",
    numStars: 6,
    starType: "Blue subgiant",
    // Per-component spectral types (α Cru system has multiple components).
    // These follow the order shown in literature: Aa, Ab, A2, C a/b, D (approx).
    // Values are illustrative and used to color/size the legend dots for the system.
    components: ["B0.5 IV", "B7?V", "B1 Vn", "B4 V", "G?V", "M0 V"],
    exo: false,
    exoCount: 0,
    notes: "Brightest in Southern Cross.",
  },
  {
    name: "Aldebaran",
    constellation: "Taurus",
    visibility: "Northern",
    mag: 0.85,
    distance: 65.0,
    lum: 440,
    temp: 3900,
    radius: 44,
    mass: 1.2,
    age: 6.6,
    spectral: "K5 III",
    numStars: 2,
    starType: "Red giant",
    exo: false,
    exoCount: 0,
    // Aldebaran has a very faint reported companion (B) catalogued in
    // double-star catalogs; there are also historic visual companions that
    // proved to be optical. Surface a conservative A+B representation and
    // keep the note about an unconfirmed planet claim.
    components: [
      { name: "A", spec: "K5 III", visualSize: 36 },
      { name: "B", spec: "M2.5 V", visualSize: 12 },
    ],
    sources: [
      "https://en.wikipedia.org/wiki/Aldebaran",
      "http://simbad.u-strasbg.fr/simbad/sim-id?Ident=Aldebaran",
    ],
    notes:
      "Orange giant; companion Aldebaran B (very faint, ~mag 13) is catalogued as part of the system; historic additional visual companions are mostly optical. Planet claim remains unconfirmed — see sources.",
  },
  {
    name: "Spica",
    constellation: "Virgo",
    visibility: "Both",
    mag: 0.98,
    distance: 250,
    lum: 12100,
    temp: 22400,
    radius: 7.5,
    mass: 11,
    age: 0.013,
    spectral: "B1 V + B2 V",
    numStars: 2,
    starType: "Spectroscopic binary",
    exo: false,
    exoCount: 0,
    // Spica is a well-known close spectroscopic binary (B1III–IV + B2V).
    // Add per-component entries and sources so UI shows the pair and we
    // preserve provenance for the binary parameters.
    components: [
      { name: "A", spec: "B1 III–IV", visualSize: 36 },
      { name: "B", spec: "B2 V", visualSize: 28 },
    ],
    sources: [
      "https://en.wikipedia.org/wiki/Spica",
      "http://simbad.u-strasbg.fr/simbad/sim-id?Ident=Spica",
    ],
    notes:
      "Massive close spectroscopic binary (B1 III–IV + B2 V). Orbital period ~4.0145 d — see sources.",
  },
  {
    name: "Antares",
    constellation: "Scorpius",
    visibility: "Southern",
    mag: 1.06,
    distance: 550,
    lum: 75000,
    temp: 3600,
    radius: 680,
    mass: 18,
    age: 0.012,
    spectral: "M1 Ib",
    numStars: 2,
    starType: "Red supergiant",
    exo: false,
    exoCount: 0,
    // Antares is a red supergiant primary with a hot, much fainter B-type
    // companion (α Sco B). The system's orbit estimates vary; flag the
    // multiplicity/orbit parameters as somewhat uncertain while recording
    // the components and sources.
    components: [
      { name: "A", spec: "M1.5 Iab (Red supergiant)", visualSize: 48 },
      { name: "B", spec: "B2.5 V", visualSize: 22 },
    ],
    uncertainty: [2],
    sources: [
      "https://en.wikipedia.org/wiki/Antares",
      "http://simbad.u-strasbg.fr/simbad/sim-id?Ident=Antares",
    ],
    notes:
      "Red supergiant primary (α Sco A) with a hot, faint B-type companion (α Sco B). Orbit solutions have varied and are considered somewhat uncertain — see sources.",
  },
  {
    name: "Pollux",
    constellation: "Gemini",
    visibility: "Northern",
    mag: 1.14,
    distance: 34,
    lum: 43,
    temp: 4865,
    radius: 8.8,
    mass: 1.9,
    age: 0.7,
    spectral: "K0 III",
    starType: "Orange giant",
    exo: true,
    exoCount: 1,
    notes: "Confirmed exoplanet Pollux b (gas giant).",
  },
  {
    name: "Fomalhaut",
    constellation: "Piscis Austrinus",
    visibility: "Southern",
    mag: 1.16,
    distance: 25,
    lum: 16,
    temp: 8590,
    radius: 1.8,
    mass: 1.9,
    age: 0.44,
    spectral: "A3 V",
    numStars: 3,
    starType: "Main sequence",
    // Represent the system components so the UI renders three illustrative dots
    // (A = primary A3 V; B = TW Piscis Austrini, K-type; C = LP 876-10, M-type).
    // These component specs are illustrative to control the on-page colors/sizes.
    components: [
      { name: "A", spec: "A3 V", visualSize: 36 },
      { name: "B", spec: "K4 V", visualSize: 14 },
      { name: "C", spec: "M4 V", visualSize: 12 },
    ],
    // There is no confirmed exoplanet around Fomalhaut in this dataset.
    exo: false,
    exoCount: 0,
    notes: "Famous debris ring; expanding dust cloud (no confirmed exoplanet).",
  },
  {
    name: "Deneb",
    constellation: "Cygnus",
    visibility: "Northern",
    mag: 1.25,
    distance: 2600,
    lum: 200000,
    temp: 8525,
    radius: 200,
    mass: 19,
    age: 0.006,
    spectral: "A2 Ia",
    starType: "White supergiant",
    uncertainty: [1, 3], // 1=distance/parallax disagreement, 3=spectral/luminosity disagreement
    sources: ["https://en.wikipedia.org/wiki/Deneb"],
    exo: false,
    exoCount: 0,
    notes: "One of the most luminous visible stars.",
  },
  {
    name: "Mimosa (Beta Crucis)",
    constellation: "Crux",
    visibility: "Southern",
    mag: 1.25,
    distance: 280,
    lum: 34000,
    temp: 27000,
    radius: 8.4,
    mass: 14,
    age: 0.008,
    spectral: "B0.5 III",
    starType: "Blue giant",
    exo: false,
    exoCount: 0,
    notes: "Bright Southern Cross member.",
  },
  {
    name: "Regulus",
    constellation: "Leo",
    visibility: "Northern",
    mag: 1.35,
    distance: 79,
    lum: 350,
    temp: 12100,
    radius: 3.1,
    mass: 3.8,
    age: 0.15,
    spectral: "B7 V",
    starType: "Main sequence",
    exo: false,
    exoCount: 0,
    notes: "Rapidly spinning, oblate star.",
  },
  {
    name: "Adhara (Epsilon CMa)",
    constellation: "Canis Major",
    visibility: "Both",
    mag: 1.5,
    distance: 430,
    lum: 38000,
    temp: 22200,
    radius: 14,
    mass: 12,
    age: 0.022,
    spectral: "B2 II",
    numStars: 2,
    starType: "Blue giant",
    exo: false,
    exoCount: 0,
    // Epsilon CMa (Adhara) is a reported visual binary: A (Adhara, the bright
    // B2 II primary) and a faint B component (~+7.5 mag) at ~7.5–7.9".
    // The pair is listed in WDS and common catalogs; record per-component
    // rendering and provenance. Keep primary numeric parameters unchanged.
    components: [
      { name: "A (Adhara)", spec: "B2 II", visualSize: 40 },
      { name: "B", spec: "~A/F (mag ~7.5)", visualSize: 12 },
    ],
    sources: [
      "https://en.wikipedia.org/wiki/Epsilon_Canis_Majoris",
      "http://simbad.u-strasbg.fr/simbad/sim-id?Ident=Epsilon+Canis+Majoris",
    ],
    notes:
      "Binary system (Adhara = ε CMa A) with a faint visual companion ε CMa B (~mag 7.5) at ~7.5–7.9 arcsec. The IAU-approved proper name 'Adhara' refers to the primary (A). Some catalogues report slightly different distance estimates (Hipparcos/Gaia reductions); see sources.",
  },
  {
    name: "Shaula (Lambda Sco)",
    constellation: "Scorpius",
    visibility: "Southern",
    mag: 1.62,
    distance: 570,
    lum: 35000,
    temp: 22000,
    radius: 8,
    mass: 11,
    age: 0.01,
    spectral: "B2 IV",
    numStars: 3,
    starType: "Blue subgiant",
    // Illustrative per-component breakdown so the UI renders three circles
    components: [
      { name: "A", spec: "B2 IV", visualSize: 20 },
      { name: "B", spec: "B3 V", visualSize: 14 },
      { name: "C", spec: "B5 V", visualSize: 12 },
    ],
    exo: false,
    exoCount: 0,
    notes: "Multiple hot system.",
  },
  {
    name: "Castor",
    constellation: "Gemini",
    visibility: "Northern",
    mag: 1.58,
    distance: 52,
    lum: 37,
    temp: 8840,
    radius: 2.4,
    mass: 2.0,
    age: 0.37,
    spectral: "A1 V",
    numStars: 6,
    starType: "Multiple (sextuple)",
    // Per-component spectral types for Castor (Aa+Ab, Ba+Bb, Ca+Cb = YY Gem).
    // According to literature/Wikipedia the bright primaries are A-type (A1V, Am)
    // and the companions are red dwarfs (dM1e); use those for accurate coloring.
    // Per-component objects include a name, spectral string and an illustrative
    // visualSize (px) to control the on-page dot size so the UI can match
    // the supplied illustration. Order: Aa, Ab, Ba, Bb, Ca, Cb.
    components: [
      { name: "Aa", spec: "A1 V", visualSize: 36 },
      { name: "Ab", spec: "dM1e", visualSize: 12 },
      { name: "Ba", spec: "Am", visualSize: 30 },
      { name: "Bb", spec: "dM1e", visualSize: 12 },
      { name: "Ca", spec: "dM1e", visualSize: 12 },
      { name: "Cb", spec: "dM1e", visualSize: 12 },
    ],
    exo: false,
    exoCount: 0,
    notes: "Complex six-star system.",
  },
  {
    name: "Gacrux (Gamma Cru)",
    constellation: "Crux",
    visibility: "Southern",
    mag: 1.63,
    distance: 88,
    lum: 820,
    temp: 3620,
    radius: 84,
    mass: 1.5,
    age: 0.1,
    spectral: "M3 III",
    starType: "Red giant",
    exo: false,
    exoCount: 0,
    notes: "Top of Southern Cross.",
  },
  // --- Additional bright stars ---
  {
    name: "Bellatrix",
    constellation: "Orion",
    visibility: "Both",
    mag: 1.64,
    distance: 244,
    lum: 900,
    temp: 22000,
    radius: 5.8,
    mass: 8.6,
    age: 0.02,
    spectral: "B2 III",
    starType: "Blue giant",
    exo: false,
    exoCount: 0,
    notes: "Left shoulder of Orion.",
  },
  {
    name: "Elnath",
    constellation: "Taurus",
    visibility: "Northern",
    mag: 1.65,
    distance: 131,
    lum: 700,
    temp: 13000,
    radius: 4.0,
    mass: 6.9,
    age: 0.03,
    spectral: "B7 III",
    starType: "Blue giant",
    exo: false,
    exoCount: 0,
    notes: "Beta Tauri, on Taurus horn.",
  },
  {
    name: "Alnilam",
    constellation: "Orion",
    visibility: "Both",
    mag: 1.69,
    distance: 1340,
    lum: 275000,
    temp: 27500,
    radius: 24,
    mass: 40,
    age: 0.005,
    spectral: "B0 Ia",
    // Alnilam is generally treated as a single blue supergiant (B0 Ia).
    // Earlier dataset incorrectly listed multiple components; update to a
    // conservative single-star representation and keep distance uncertainty.
    numStars: 1,
    starType: "Blue supergiant",
    uncertainty: [1], // distance/parallax disagreement in literature
    sources: [
      "https://en.wikipedia.org/wiki/Alnilam",
      "http://simbad.u-strasbg.fr/simbad/sim-id?Ident=Epsilon+Orionis",
    ],
    exo: false,
    exoCount: 0,
    notes:
      "Middle star of Orion's Belt. Treated as a single blue supergiant in major catalogs; distance estimates vary between sources.",
  },
  {
    name: "Alnitak",
    constellation: "Orion",
    visibility: "Both",
    mag: 1.74,
    distance: 820,
    lum: 100000,
    temp: 30000,
    radius: 20,
    mass: 30,
    age: 0.006,
    spectral: "O9.7 Ib",
    numStars: 3,
    starType: "Blue supergiant",
    // Alnitak is a hierarchical triple: Alnitak Aa (primary, O9.5–O9.7 Iab)
    // with a close companion Ab, plus a wider visual companion B. Add
    // per-component entries so the UI renders three dots and include
    // authoritative sources.
    uncertainty: [1, 2], // distance disagreement; multiplicity details
    sources: [
      "https://en.wikipedia.org/wiki/Alnitak",
      "http://simbad.u-strasbg.fr/simbad/sim-id?Ident=Zeta+Orionis",
    ],
    components: [
      { name: "Aa", spec: "O9.5 Iab", visualSize: 40 },
      { name: "Ab", spec: "B1 IV", visualSize: 22 },
      { name: "B", spec: "B0–B1 III", visualSize: 18 },
    ],
    exo: false,
    exoCount: 0,
    notes:
      "Left-most of Orion's Belt. Alnitak A is itself a close pair (Aa+Ab) with a wider visual B companion; some faint line-of-sight stars are not physically associated.",
  },
  {
    name: "Mintaka",
    constellation: "Orion",
    visibility: "Both",
    mag: 2.23,
    distance: 915,
    lum: 90000,
    temp: 31000,
    radius: 18,
    mass: 30,
    age: 0.006,
    spectral: "O9.5 II",
    // Mintaka (δ Ori) is a complex hierarchical system. Recent references
    // describe the system as comprising the close eclipsing pair Aa1+Aa2,
    // a resolved Ab, and additional components C (which itself is a close
    // binary) and a B component whose physical association is debated.
    // Represent the commonly cited components conservatively and flag
    // uncertain associations.
    numStars: 5,
    starType: "Multiple (hierarchy)",
    uncertainty: [1, 2], // distance discrepancies; some companions' association disputed
    sources: [
      "https://en.wikipedia.org/wiki/Mintaka",
      "http://simbad.u-strasbg.fr/simbad/sim-id?Ident=Delta+Orionis",
    ],
    components: [
      { name: "Aa1", spec: "O9.5 II", visualSize: 40 },
      { name: "Aa2", spec: "B1 V", visualSize: 30 },
      { name: "Ab", spec: "B0 IV", visualSize: 22 },
      // Delta Ori C is often listed as a close binary (Ca+Cb); represent
      // it here as two components so the UI renders the multiplicity.
      { name: "Ca", spec: "B-type", visualSize: 16 },
      { name: "Cb", spec: "B-type", visualSize: 14 },
    ],
    exo: false,
    exoCount: 0,
    notes:
      "Right-most of Orion's Belt. Hierarchical multiple: Aa1+Aa2 (eclipsing), Ab (resolved), and C (itself a close pair); the B component's physical association is debated — see sources.",
  },
  {
    name: "Saiph",
    constellation: "Orion",
    visibility: "Both",
    mag: 2.06,
    distance: 720,
    lum: 85000,
    temp: 26000,
    radius: 22,
    mass: 25,
    age: 0.007,
    spectral: "B0.5 Ia",
    starType: "Supergiant",
    numStars: 1,
    uncertainty: [1], // distance estimate varies between sources
    sources: ["https://en.wikipedia.org/wiki/Saiph"],
    exo: false,
    exoCount: 0,
    notes: "Knee of Orion.",
  },
  {
    name: "Alkaid",
    constellation: "Ursa Major",
    visibility: "Northern",
    mag: 1.86,
    distance: 101,
    lum: 300,
    temp: 20000,
    radius: 3.6,
    mass: 6.0,
    age: 0.1,
    spectral: "B3 V",
    starType: "Main sequence",
    exo: false,
    exoCount: 0,
    notes: "End of the Big Dipper's handle.",
  },
  {
    name: "Mizar",
    constellation: "Ursa Major",
    visibility: "Northern",
    mag: 2.23,
    distance: 78,
    lum: 50,
    temp: 9000,
    radius: 3.0,
    mass: 3.5,
    age: 0.4,
    spectral: "A2 V",
    numStars: 4,
    starType: "Multiple (quadruple)",
    // Mizar is a well-known quadruple: ζ1 (Mizar A) = Aa+Ab (both A2Vp)
    // and ζ2 (Mizar B) = Ba+Bb (Ba shows Am characteristics; Bb is faint).
    // Add per-component entries so the UI renders four colored dots.
    sources: [
      "https://en.wikipedia.org/wiki/Mizar",
      "http://simbad.u-strasbg.fr/simbad/sim-id?Ident=Mizar",
    ],
    components: [
      { name: "Aa", spec: "A2Vp", visualSize: 30 },
      { name: "Ab", spec: "A2Vp", visualSize: 30 },
      { name: "Ba", spec: "kA1h(eA)mA7IV-V", visualSize: 26 },
      { name: "Bb", spec: "", visualSize: 12 },
    ],
    exo: false,
    exoCount: 0,
    notes:
      "Quadruple system: Mizar Aa+Ab (A2Vp) and Ba+Bb (Ba: Am, Bb: faint companion). Sources: Wikipedia, SIMBAD.",
  },
  {
    name: "Alioth",
    constellation: "Ursa Major",
    visibility: "Northern",
    mag: 1.76,
    distance: 82,
    lum: 102,
    temp: 9500,
    radius: 3.2,
    mass: 3.0,
    age: 0.3,
    spectral: "A0p",
    starType: "Main sequence",
    exo: false,
    exoCount: 0,
    notes: "Brightest of the Plough's handle stars.",
  },
  {
    name: "Dubhe",
    constellation: "Ursa Major",
    visibility: "Northern",
    mag: 1.79,
    distance: 124,
    lum: 360,
    temp: 9000,
    radius: 25,
    mass: 4.25,
    age: 0.1,
    spectral: "K0 III",
    numStars: 4,
    starType: "Giant",
    exo: false,
    exoCount: 0,
    // Conservative per-component breakdown for the Dubhe system (α UMa).
    // Literature identifies the bright pair α UMa A (K0 III) + α UMa B (A-type
    // main-sequence) with a ~44.45 yr orbit, plus a widely-separated F-type
    // spectroscopic pair (HD 95638) sometimes catalogued as a companion. The
    // wide pair's membership is debated (~40% chance of being unrelated), so
    // include an `uncertainty` flag and `sources` for verification.
    uncertainty: [2], // 2 = multiplicity/association disputed
    sources: [
      "https://en.wikipedia.org/wiki/Dubhe",
      "http://simbad.u-strasbg.fr/simbad/sim-id?Ident=alpha+ursae+majoris",
    ],
    components: [
      { name: "A", spec: "K0 III", visualSize: 36 },
      { name: "B", spec: "A5 V", visualSize: 18 },
      // The following represent the widely-separated F-type pair (HD 95638),
      // sometimes treated as α UMa C (itself a short-period spectroscopic
      // binary). We model them as Ca/Cb for the UI so the system renders as
      // a quadruple; membership is deliberately flagged as uncertain.
      { name: "Ca", spec: "F8 V", visualSize: 12 },
      { name: "Cb", spec: "F8 V", visualSize: 12 },
    ],
    notes:
      "Multiple system: A (K0 III) + B (A-type) with ~44.45 yr orbit; a distant F-type spectroscopic pair (HD 95638) is sometimes catalogued as a companion — membership uncertain. Sources: Wikipedia, SIMBAD.",
  },
  {
    name: "Merak",
    constellation: "Ursa Major",
    visibility: "Northern",
    mag: 2.37,
    distance: 79,
    lum: 70,
    temp: 9000,
    radius: 3.0,
    mass: 3.0,
    age: 0.4,
    spectral: "A1 V",
    starType: "Main sequence",
    exo: false,
    exoCount: 0,
    notes: "Pointer star in the Big Dipper.",
  },
  {
    name: "Phecda",
    constellation: "Ursa Major",
    visibility: "Northern",
    mag: 2.44,
    distance: 83,
    lum: 60,
    temp: 9000,
    radius: 2.6,
    mass: 2.5,
    age: 0.5,
    spectral: "A0 V",
    starType: "Main sequence",
    exo: false,
    exoCount: 0,
    notes: "Part of the Plough bowl.",
  },
  {
    name: "Polaris",
    constellation: "Ursa Minor",
    visibility: "Northern",
    mag: 1.98,
    distance: 433,
    lum: 2500,
    temp: 6015,
    radius: 46,
    mass: 5.4,
    age: 0.07,
    spectral: "F7 Ib",
    numStars: 3,
    starType: "Cepheid/supergiant",
    exo: false,
    exoCount: 0,
    // Polaris is a hierarchical triple: the Cepheid primary (Aa) with a
    // close spectroscopic companion Ab, and a distant resolved companion B.
    // Distance/parameter estimates have been debated in literature; flag
    // distance uncertainty conservatively.
    components: [
      { name: "Aa", spec: "F7 Ib (Cepheid)", visualSize: 44 },
      { name: "Ab", spec: "F6 V (spectroscopic)", visualSize: 16 },
      { name: "B", spec: "F3 V (resolved)", visualSize: 18 },
    ],
    uncertainty: [1],
    sources: [
      "https://en.wikipedia.org/wiki/Polaris",
      "http://simbad.u-strasbg.fr/simbad/sim-id?Ident=Polaris",
    ],
    notes:
      "Triple system: Polaris Aa (Cepheid, F7 Ib) with close companion Ab (spectroscopic) and a distant resolved companion B. Distance and some parameter estimates have varied between studies; see sources.",
  },
  {
    name: "Denebola",
    constellation: "Leo",
    visibility: "Northern",
    mag: 2.14,
    distance: 36,
    lum: 15,
    temp: 8500,
    radius: 1.7,
    mass: 1.8,
    age: 0.5,
    spectral: "A3 V",
    starType: "Main sequence",
    exo: false,
    exoCount: 0,
    notes: "Tail of Leo.",
  },
  {
    name: "Mirfak",
    constellation: "Perseus",
    visibility: "Northern",
    mag: 1.79,
    distance: 590,
    lum: 4000,
    temp: 8000,
    radius: 30,
    mass: 12,
    age: 0.02,
    spectral: "F5 Ib",
    starType: "Supergiant",
    uncertainty: [1], // file distance differs from common literature value (~510 ly)
    sources: ["https://en.wikipedia.org/wiki/Alpha_Persei"],
    exo: false,
    exoCount: 0,
    notes: "Alpha Persei cluster member.",
  },
  {
    name: "Kaus Australis",
    constellation: "Sagittarius",
    visibility: "Southern",
    mag: 1.79,
    distance: 82,
    lum: 120,
    temp: 12000,
    radius: 4.5,
    mass: 5.5,
    age: 0.1,
    spectral: "B9 II",
    starType: "Bright giant",
    uncertainty: [1], // distance in file differs from some catalog values
    sources: ["https://en.wikipedia.org/wiki/Kaus_Australis"],
    exo: false,
    exoCount: 0,
    notes: "Brightest in Sagittarius.",
  },
  {
    name: "Avior",
    constellation: "Carina",
    visibility: "Southern",
    mag: 1.86,
    distance: 630,
    lum: 9000,
    temp: 20000,
    radius: 12,
    mass: 15,
    age: 0.01,
    spectral: "B2 IV",
    starType: "Blue subgiant",
    exo: false,
    exoCount: 0,
    notes: "Bright southern star near Canopus.",
  },
  {
    name: "Miaplacidus",
    constellation: "Carina",
    visibility: "Southern",
    mag: 1.67,
    distance: 111,
    lum: 400,
    temp: 8500,
    radius: 3.5,
    mass: 3.2,
    age: 0.3,
    spectral: "A2 II",
    starType: "Bright giant",
    exo: false,
    exoCount: 0,
    notes: "Second-brightest in Carina region.",
  },
  {
    name: "Menkent",
    constellation: "Centaurus",
    visibility: "Southern",
    mag: 2.06,
    distance: 60,
    lum: 160,
    temp: 5600,
    radius: 12,
    mass: 2.8,
    age: 0.25,
    spectral: "K0 III",
    starType: "Giant",
    exo: false,
    exoCount: 0,
    notes: "Theta Centauri.",
  },
  {
    name: "Alpheratz",
    constellation: "Andromeda",
    visibility: "Northern",
    mag: 2.06,
    distance: 97,
    lum: 400,
    temp: 9000,
    radius: 3.2,
    mass: 3.4,
    age: 0.3,
    spectral: "B8 IV",
    starType: "Subgiant",
    exo: false,
    exoCount: 0,
    notes: "Part of the Great Square of Pegasus.",
  },
  {
    name: "Algol",
    constellation: "Perseus",
    visibility: "Northern",
    mag: 2.12,
    distance: 93,
    lum: 150,
    temp: 13000,
    radius: 3.0,
    mass: 3.6,
    age: 0.5,
    spectral: "B8 V",
    numStars: 3,
    starType: "Eclipsing binary (triple)",
    exo: false,
    exoCount: 0,
    // Algol is a classic hierarchical triple: an eclipsing close pair (Aa1+Aa2)
    // plus a more distant third component Ab. Add per-component entries
    // so UI shows three dots and include provenance.
    components: [
      { name: "Aa1", spec: "B8 V", visualSize: 30 },
      { name: "Aa2", spec: "K0 IV", visualSize: 20 },
      { name: "Ab", spec: "F1 V", visualSize: 22 },
    ],
    sources: [
      "https://en.wikipedia.org/wiki/Algol",
      "http://simbad.u-strasbg.fr/simbad/sim-id?Ident=Algol",
    ],
    notes:
      "Triple system: Algol Aa1+Aa2 form the close eclipsing binary; Algol Ab is a third component on a longer orbit. The system defines the 'Algol-type' eclipsing variables — see sources.",
  },
  {
    name: "Schedar",
    constellation: "Cassiopeia",
    visibility: "Northern",
    mag: 2.24,
    distance: 230,
    lum: 1200,
    temp: 4750,
    radius: 35,
    mass: 5.0,
    age: 0.08,
    spectral: "K0 III",
    starType: "Giant",
    exo: false,
    exoCount: 0,
    notes: "Alpha Cassiopeiae.",
  },
  {
    name: "Caph",
    constellation: "Cassiopeia",
    visibility: "Northern",
    mag: 2.27,
    distance: 54,
    lum: 80,
    temp: 6000,
    radius: 4.0,
    mass: 2.0,
    age: 0.7,
    spectral: "F2 III",
    starType: "Giant/subgiant",
    exo: false,
    exoCount: 0,
    notes: "Part of the W of Cassiopeia.",
  },
  // --- Added: next brightest stars ---
  {
    name: "Nunki (Sigma Sagittarii)",
    constellation: "Sagittarius",
    visibility: "Southern",
    mag: 2.05,
    distance: 230,
    spectral: "B2.5 V",
    starType: "Main sequence",
    // Populated from Wikipedia infobox / cited catalogs (see sources).
    temp: 18890,
    radius: 4.1,
    mass: 6.5,
    age: 0.0314,
    lum: 631,
    exo: false,
    exoCount: 0,
    sources: [
      "https://en.wikipedia.org/wiki/Nunki",
      "http://simbad.u-strasbg.fr/simbad/sim-id?Ident=Sigma+Sagittarii",
    ],
    notes:
      "Bright B-type main-sequence star in Sagittarius (often called Nunki). Distance and catalog values vary between sources; see source.",
  },
  {
    name: "Mirach (Beta Andromedae)",
    constellation: "Andromeda",
    visibility: "Northern",
    mag: 2.07,
    distance: 200,
    spectral: "M0 III",
    starType: "Red giant",
    temp: 3762,
    radius: 86.4,
    mass: 2.49,
    age: 2.5,
    lum: 1675,
    exo: false,
    exoCount: 0,
    sources: [
      "https://en.wikipedia.org/wiki/Mirach",
      "http://simbad.u-strasbg.fr/simbad/sim-id?Ident=Mirach",
    ],
    uncertainty: [4, 5],
    notes:
      "Red giant (β And) on asymptotic giant branch. Apparent V varies slightly (reported ~2.01–2.10 in literature). Has brown dwarf companion. Age estimated from AGB evolutionary models.",
  },
  {
    name: "Rasalhague (Alpha Ophiuchi)",
    constellation: "Ophiuchus",
    visibility: "Northern",
    mag: 2.07,
    distance: 47,
    spectral: "A5 IVnn",
    starType: "Subgiant",
    // Rapid rotator (oblate): Wikipedia lists polar/equatorial radii and temperatures.
    // We store a representative (average) radius and the literature "true" effective
    // temperature when available. See sources for polar/equatorial breakdown.
    temp: 8336,
    radius: 2.623,
    mass: 2.2,
    age: 0.77,
    lum: 31.3,
    exo: false,
    exoCount: 0,
    sources: [
      "https://en.wikipedia.org/wiki/Rasalhague",
      "http://simbad.u-strasbg.fr/simbad/sim-id?Ident=Rasalhague",
    ],
    notes:
      "Rapidly rotating subgiant and the brightest star in Ophiuchus; classifications and distances from catalogs may vary. Added SIMBAD link for catalog photometry.",
  },
  {
    name: "Algieba (Gamma Leonis)",
    constellation: "Leo",
    visibility: "Northern",
    mag: 2.08,
    distance: 130,
    spectral: "K0 III",
    numStars: 2,
    starType: "Giant (binary)",
    // Values from Wikipedia infobox / referenced catalog entries (primary component)
    temp: 4457,
    radius: 29,
    mass: 1.66,
    age: 1.75,
    lum: 250,
    components: [
      { name: "A", spec: "K0 III", visualSize: 30 },
      { name: "B", spec: "G7 IIIb", visualSize: 22 },
    ],
    exo: false,
    exoCount: 0,
    sources: [
      "https://en.wikipedia.org/wiki/Algieba",
      "http://simbad.u-strasbg.fr/simbad/sim-id?Ident=Gamma+Leonis",
    ],
    uncertainty: [5],
    notes:
      "Bright binary in Leo (γ Leo). Component mags and Hipparcos/ catalogue values differ slightly (see sources); added SIMBAD for photometric/catalog reference.",
  },
  {
    name: "Kochab (Beta Ursae Minoris)",
    constellation: "Ursa Minor",
    visibility: "Northern",
    mag: 2.08,
    distance: 130,
    spectral: "K4 III",
    starType: "Red giant",
    // Adopted values from Wikipedia table (interferometric/catalog results).
    temp: 4008,
    radius: 44.13,
    mass: 1.3,
    age: 2.95,
    lum: 454,
    exo: false,
    exoCount: 0,
    sources: [
      "https://en.wikipedia.org/wiki/Kochab",
      "http://simbad.u-strasbg.fr/simbad/sim-id?Ident=Kochab",
    ],
    notes:
      "Bright K-type giant in Ursa Minor; historic pole-star companion of Polaris in ancient epochs. Added SIMBAD link for catalog photometry.",
  },
  // --- Appended additional bright stars ---
  {
    name: "Tiaki (Beta Gruis)",
    constellation: "Grus",
    visibility: "Southern",
    mag: 2.15,
    distance: 170,
    spectral: "M5 III",
    starType: "Red giant",
    temp: 3508,
    radius: 154,
    mass: 2.4,
    age: 0.45,
    lum: 3221,
    exo: false,
    exoCount: 0,
    sources: [
      "https://en.wikipedia.org/wiki/Beta_Gruis",
      "http://simbad.u-strasbg.fr/simbad/sim-id?Ident=Beta+Gruis",
    ],
    notes:
      "Also known as Tiaki (β Gruis). Bright southern red giant; added for top-60 coverage.",
  },
  {
    name: "Muhlifain (Gamma Centauri)",
    constellation: "Centaurus",
    visibility: "Southern",
    mag: 2.17,
    distance: 130,
    spectral: "A0 III",
    starType: "Giant",
    temp: 9300,
    radius: 3.8,
    mass: 2.8,
    age: 0.8,
    lum: 95,
    exo: false,
    exoCount: 0,
    sources: [
      "https://en.wikipedia.org/wiki/Gamma_Centauri",
      "http://simbad.u-strasbg.fr/simbad/sim-id?Ident=Gamma+Centauri",
    ],
    uncertainty: [4],
    notes:
      "Also called Muhlifain (γ Centauri). Binary system with 84.5-year orbit; both A-type subgiants. Age estimated from A-type subgiant evolution.",
  },
  {
    name: "Aspidiske (Iota Carinae)",
    constellation: "Carina",
    visibility: "Southern",
    mag: 2.21,
    distance: 690,
    spectral: "A9 Ib",
    starType: "Supergiant",
    temp: 7500,
    radius: 48.25,
    mass: 6.9,
    age: 0.056,
    lum: 4900,
    exo: false,
    exoCount: 0,
    sources: [
      "https://en.wikipedia.org/wiki/Iota_Carinae",
      "http://simbad.u-strasbg.fr/simbad/sim-id?Ident=Iota+Carinae",
    ],
    notes:
      "Proper name Aspidiske (ι Car). Bright southern supergiant; included to reach 60 entries.",
  },
  {
    name: "Suhail (Lambda Velorum)",
    constellation: "Vela",
    visibility: "Southern",
    mag: 2.21,
    distance: 570,
    spectral: "K4 Ib",
    starType: "Bright giant",
    temp: 3835,
    radius: 211,
    mass: 7.0,
    age: 0.0316,
    lum: 8300,
    exo: false,
    exoCount: 0,
    sources: [
      "https://en.wikipedia.org/wiki/Lambda_Velorum",
      "http://simbad.u-strasbg.fr/simbad/sim-id?Ident=Lambda+Velorum",
    ],
    notes: "Also known as Suhail (λ Velorum). Included for top-60 coverage.",
  },
  {
    name: "Alphecca (Alpha Coronae Borealis)",
    constellation: "Corona Borealis",
    visibility: "Northern",
    mag: 2.23,
    distance: 75,
    spectral: "A0 V",
    starType: "Main sequence",
    temp: 9700,
    radius: 3.059,
    mass: 2.581,
    age: 0.4,
    lum: 74,
    exo: false,
    exoCount: 0,
    sources: [
      "https://en.wikipedia.org/wiki/Alphecca",
      "http://simbad.u-strasbg.fr/simbad/sim-id?Ident=Alpha+Coronae+Borealis",
    ],
    notes:
      "Also called Alphecca (α CrB, Gemma). Added to expand to 60 brightest.",
  },
  {
    name: "Almach (Gamma Andromedae)",
    constellation: "Andromeda",
    visibility: "Northern",
    mag: 2.26,
    distance: 350,
    spectral: "K3 II",
    starType: "Bright giant",
    // Representative values for the bright giant primary (γ1 And)
    temp: 4248,
    radius: 98.5,
    mass: 3.3,
    age: 1.5,
    lum: 2987,
    exo: false,
    exoCount: 0,
    sources: [
      "https://en.wikipedia.org/wiki/Almach",
      "http://simbad.u-strasbg.fr/simbad/sim-id?Ident=Gamma+Andromedae",
    ],
    uncertainty: [4],
    notes:
      "Also called Almach (γ And). Quadruple star system; primary is post-AGB candidate bright giant. Age estimated from post-AGB evolutionary models.",
  },
  {
    name: "Sadr (Gamma Cygni)",
    constellation: "Cygnus",
    visibility: "Northern",
    mag: 2.23,
    distance: 1500,
    spectral: "F8 Iab",
    starType: "Yellow supergiant",
    temp: 5790,
    radius: 183,
    mass: 14.5,
    age: 0.012,
    lum: 33023,
    exo: false,
    exoCount: 0,
    sources: [
      "https://en.wikipedia.org/wiki/Gamma_Cygni",
      "http://simbad.u-strasbg.fr/simbad/sim-id?Ident=Gamma+Cygni",
    ],
    notes:
      "Sadr (γ Cygni), central star of the Northern Cross; bright yellow supergiant. Added to include ranks 61–70.",
  },
  {
    name: "Eltanin (Gamma Draconis)",
    constellation: "Draco",
    visibility: "Northern",
    mag: 2.23,
    distance: 150,
    spectral: "K5 III",
    starType: "Red giant",
    temp: 3964,
    radius: 51.8,
    mass: 2.14,
    age: 1.3,
    lum: 598,
    exo: false,
    exoCount: 0,
    sources: [
      "https://en.wikipedia.org/wiki/Gamma_Draconis",
      "http://simbad.u-strasbg.fr/simbad/sim-id?Ident=Gamma+Draconis",
    ],
    notes:
      "Eltanin (γ Draconis), bright K-type giant near the head of Draco. Added to include ranks 61–70.",
  },
  // --- Newly added bright stars (next 10 missing from the Wikipedia list) ---
  {
    name: "Alnair (Alpha Gruis)",
    constellation: "Grus",
    visibility: "Southern",
    mag: 1.74,
    distance: 101,
    lum: 520,
    temp: 14245,
    radius: 3.91,
    mass: 3.82,
    age: 0.1,
    spectral: "B6 V",
    starType: "Main sequence",
    exo: false,
    exoCount: 0,
    sources: [
      "https://en.wikipedia.org/wiki/Alpha_Gruis",
      "http://simbad.u-strasbg.fr/simbad/sim-id?Ident=Alpha+Gruis",
    ],
    notes:
      "Alnair (α Gru), bright B-type star in Grus; values from Wikipedia infobox and SIMBAD.",
  },
  {
    name: "Wezen (Delta Canis Majoris)",
    constellation: "Canis Major",
    visibility: "Southern",
    mag: 1.83,
    distance: 1600,
    lum: 34600,
    temp: 5818,
    radius: 188,
    mass: 14.5,
    age: 0.012,
    spectral: "F8 Ia",
    starType: "Supergiant",
    exo: false,
    exoCount: 0,
    sources: [
      "https://en.wikipedia.org/wiki/Delta_Canis_Majoris",
      "http://simbad.u-strasbg.fr/simbad/sim-id?Ident=Delta+Canis+Majoris",
    ],
    notes:
      "Wezen (δ CMa) — luminous F-type supergiant. Distance and parameters per Wikipedia; catalog values vary between sources.",
  },
  {
    name: "Sargas (Theta Scorpii)",
    constellation: "Scorpius",
    visibility: "Southern",
    mag: 1.87,
    distance: 329,
    lum: 1400,
    temp: 6294,
    radius: 31,
    mass: 3.1,
    age: 1.2,
    spectral: "F1 III",
    starType: "Bright giant",
    exo: false,
    exoCount: 0,
    sources: [
      "https://en.wikipedia.org/wiki/Theta_Scorpii",
      "http://simbad.u-strasbg.fr/simbad/sim-id?Ident=Theta+Scorpii",
    ],
    uncertainty: [4],
    notes:
      "Sargas (θ Sco). Rapidly rotating oblate bright giant; suspected post-merger star from binary coalescence. Age estimated from F-type giant evolution.",
  },
  {
    name: "Menkalinan (Beta Aurigae)",
    constellation: "Auriga",
    visibility: "Northern",
    mag: 1.9,
    distance: 81.1,
    // Representative primary component values (system is an eclipsing binary)
    lum: 47,
    temp: 8985,
    radius: 2.762,
    mass: 2.389,
    age: 0.45,
    spectral: "A1mIV + A1mIV",
    numStars: 2,
    starType: "Eclipsing binary",
    components: [
      { name: "Aa", spec: "A1mIV", visualSize: 30 },
      { name: "Ab", spec: "A1mIV", visualSize: 28 },
    ],
    exo: false,
    exoCount: 0,
    sources: [
      "https://en.wikipedia.org/wiki/Beta_Aurigae",
      "http://simbad.u-strasbg.fr/simbad/sim-id?Ident=Beta+Aurigae",
    ],
    notes:
      "Menkalinan (β Aur) is a well-studied eclipsing binary; primary-component values used for the system entry.",
  },
  {
    name: "Atria (Alpha Trianguli Australis)",
    constellation: "Triangulum Australe",
    visibility: "Southern",
    mag: 1.91,
    distance: 391,
    lum: 4634,
    temp: 4043,
    radius: 139,
    mass: 6.4,
    age: 0.048,
    spectral: "K2 IIb-IIIa",
    starType: "Bright/Red giant",
    exo: false,
    exoCount: 0,
    sources: [
      "https://en.wikipedia.org/wiki/Alpha_Trianguli_Australis",
      "http://simbad.u-strasbg.fr/simbad/sim-id?Ident=Alpha+Trianguli+Australis",
    ],
    notes:
      "Atria (α TrA) — red bright giant/supergiant; values from Wikipedia infobox and recent literature.",
  },
  {
    name: "Alhena (Gamma Geminorum)",
    constellation: "Gemini",
    visibility: "Northern",
    mag: 1.9,
    distance: 109,
    lum: 207.3,
    temp: 9190,
    radius: 5.16,
    mass: 2.81,
    age: 0.6,
    spectral: "A0 IV",
    starType: "Subgiant",
    exo: false,
    exoCount: 0,
    sources: [
      "https://en.wikipedia.org/wiki/Gamma_Geminorum",
      "http://simbad.u-strasbg.fr/simbad/sim-id?Ident=Gamma+Geminorum",
    ],
    uncertainty: [4],
    notes:
      "Alhena (γ Gem) — A-type subgiant; spectroscopic binary with 12.6 year highly eccentric orbit. Age estimated from subgiant evolution.",
  },
  {
    name: "Peacock (Alpha Pavonis)",
    constellation: "Pavo",
    visibility: "Southern",
    mag: 1.94,
    distance: 179,
    lum: 2200,
    temp: 17711,
    radius: 4.83,
    mass: 5.91,
    age: 0.048,
    spectral: "B3 V",
    starType: "Main sequence / binary",
    numStars: 2,
    exo: false,
    exoCount: 0,
    sources: [
      "https://en.wikipedia.org/wiki/Alpha_Pavonis",
      "http://simbad.u-strasbg.fr/simbad/sim-id?Ident=Alpha+Pavonis",
    ],
    notes:
      "Peacock (α Pav) — bright B-type system; primary-component representative values used.",
  },
  {
    name: "Alsephina (Delta Velorum)",
    constellation: "Vela",
    visibility: "Southern",
    mag: 1.96,
    distance: 80.6,
    lum: 67,
    temp: 9440,
    radius: 2.88,
    mass: 2.43,
    age: 0.4,
    spectral: "A1 Va",
    numStars: 3,
    starType: "Multiple (eclipsing+visual)",
    components: [
      { name: "Aa", spec: "A2 IV", visualSize: 30 },
      { name: "Ab", spec: "A4 V", visualSize: 26 },
      { name: "B", spec: "F8 V", visualSize: 14 },
    ],
    exo: false,
    exoCount: 0,
    sources: [
      "https://en.wikipedia.org/wiki/Delta_Velorum",
      "http://simbad.u-strasbg.fr/simbad/sim-id?Ident=Delta+Velorum",
    ],
    notes:
      "Alsephina (δ Vel) — multiple system (eclipsing pair + visual components); primary component numbers used as representative.",
  },
  {
    name: "Mirzam (Beta Canis Majoris)",
    constellation: "Canis Major",
    visibility: "Southern",
    mag: 1.99,
    distance: 490,
    lum: 25700,
    temp: 25180,
    radius: 8.44,
    mass: 13,
    age: 0.013,
    spectral: "B1 II-III",
    starType: "Bright giant",
    exo: false,
    exoCount: 0,
    sources: [
      "https://en.wikipedia.org/wiki/Beta_Canis_Majoris",
      "http://simbad.u-strasbg.fr/simbad/sim-id?Ident=Beta+Canis+Majoris",
    ],
    notes:
      "Mirzam (β CMa) — Beta Cephei variable; values from Wikipedia infobox and SIMBAD.",
  },
  {
    name: "Naos (Zeta Puppis)",
    constellation: "Puppis",
    visibility: "Southern",
    mag: 2.25,
    distance: 1080,
    // bolometric luminosity per literature; distance remains debated in sources
    lum: 446700,
    temp: 40000,
    radius: 13.72,
    mass: 25.3,
    age: 0.003,
    spectral: "O4 If(n)p",
    starType: "Blue supergiant",
    uncertainty: [1],
    exo: false,
    exoCount: 0,
    sources: [
      "https://en.wikipedia.org/wiki/Zeta_Puppis",
      "http://simbad.u-strasbg.fr/simbad/sim-id?Ident=Zeta+Puppis",
    ],
    notes:
      "Naos (ζ Pup) — hot O-type supergiant; distance and bolometric luminosity sensitive to adopted parallax (see sources).",
  },
  {
    name: "Alphard",
    constellation: "Hydra",
    visibility: "Both",
    mag: 2.0,
    distance: 177,
    lum: 971,
    temp: 4117,
    radius: 57.6,
    mass: 3.2,
    age: 0.42,
    spectral: "K3 IIIa",
    starType: "Giant",
    exo: false,
    exoCount: 0,
    sources: [
      "https://en.wikipedia.org/wiki/Alphard",
      "http://simbad.u-strasbg.fr/simbad/sim-id?Ident=Alphard",
    ],
    notes:
      "Alphard (α Hya) — K-type giant; displays mild barium excess suggesting past mass transfer. Multi-periodic oscillations observed.",
  },
  {
    name: "Hamal",
    constellation: "Aries",
    visibility: "Northern",
    mag: 2.0,
    distance: 65.8,
    lum: 91,
    temp: 4411,
    radius: 15.2,
    mass: 1.65,
    age: 3.4,
    spectral: "K2 III Ca-1",
    starType: "Giant",
    exo: true,
    exoCount: 1,
    sources: [
      "https://en.wikipedia.org/wiki/Hamal",
      "http://simbad.u-strasbg.fr/simbad/sim-id?Ident=Hamal",
    ],
    notes:
      "Hamal (α Ari) — K-type red giant; hosts one confirmed planet (Hamal b) with mass ≥1.8 MJ. Suspected slight variability.",
  },
  {
    name: "Diphda",
    constellation: "Cetus",
    visibility: "Both",
    mag: 2.02,
    distance: 96.3,
    lum: 150,
    temp: 4797,
    radius: 17.5,
    mass: 3.5,
    age: 0.46,
    spectral: "K0 III",
    starType: "Red clump giant",
    exo: false,
    exoCount: 0,
    sources: [
      "https://en.wikipedia.org/wiki/Beta_Ceti",
      "http://simbad.u-strasbg.fr/simbad/sim-id?Ident=Beta+Ceti",
    ],
    notes:
      "Diphda (β Cet, Beta Ceti) — red clump giant (post helium-flash); shows flaring activity with multi-day outbursts. Strong X-ray emission.",
  },
  {
    name: "Dschubba",
    constellation: "Scorpius",
    visibility: "Southern",
    mag: 2.3,
    distance: 444,
    lum: 38000,
    temp: 27400,
    radius: 8.5,
    mass: 13,
    age: 0.009,
    spectral: "B0.3 IV",
    numStars: 2,
    starType: "Subgiant",
    exo: false,
    exoCount: 0,
    components: [
      { name: "A", spec: "B0.3 IV", visualSize: 1 },
      { name: "B", spec: "~B", visualSize: 0.45 },
    ],
    uncertainty: [4],
    sources: [
      "https://en.wikipedia.org/wiki/Delta_Scorpii",
      "http://simbad.u-strasbg.fr/simbad/sim-id?Ident=Delta+Scorpii",
    ],
    notes:
      "Dschubba (δ Sco, Delta Scorpii) — Be star binary; showed outburst in 2000 reaching mag 1.6. Variable Gamma Cassiopeiae type. Member of Upper Scorpius OB association.",
  },
  {
    name: "Larawag",
    constellation: "Scorpius",
    visibility: "Southern",
    mag: 2.29,
    distance: 63.7,
    lum: 60,
    temp: 4522,
    radius: 12.65,
    mass: 1.31,
    age: 3.92,
    spectral: "K1 III",
    starType: "Horizontal branch",
    exo: false,
    exoCount: 0,
    sources: [
      "https://en.wikipedia.org/wiki/Epsilon_Scorpii",
      "http://simbad.u-strasbg.fr/simbad/sim-id?Ident=Epsilon+Scorpii",
    ],
    notes:
      "Larawag (ε Sco, Epsilon Scorpii) — K-type giant on horizontal branch (red clump); fusing helium in core. Suspected slight variability.",
  },
  {
    name: "Ankaa",
    constellation: "Phoenix",
    visibility: "Southern",
    mag: 2.377,
    distance: 85,
    lum: 83,
    temp: 4700,
    radius: 14.7,
    mass: 2.79,
    age: 2.0,
    spectral: "K0.5 IIIb",
    numStars: 2,
    starType: "Giant",
    exo: false,
    exoCount: 0,
    components: [
      { name: "Ankaa A", spec: "K0.5 IIIb", visualSize: 1.2 },
      { name: "Ankaa B", spec: "~G/K?", visualSize: 0.6 },
    ],
    sources: [
      "https://en.wikipedia.org/wiki/Alpha_Phoenicis",
      "http://simbad.u-strasbg.fr/simbad/sim-id?Ident=Alpha+Phoenicis",
    ],
    uncertainty: [4],
    notes:
      "Ankaa (α Phe, Alpha Phoenicis) — spectroscopic binary system with 10.5-year orbital period; primary is K-type giant. Age estimated from K-giant evolution.",
  },
  {
    name: "Enif",
    constellation: "Pegasus",
    visibility: "Northern",
    mag: 2.4,
    distance: 690,
    lum: 8500,
    temp: 4100,
    radius: 183,
    mass: 11.5,
    age: 0.02,
    spectral: "K2 Ib",
    starType: "Red supergiant",
    exo: false,
    exoCount: 0,
    uncertainty: [4],
    sources: [
      "https://en.wikipedia.org/wiki/Epsilon_Pegasi",
      "http://simbad.u-strasbg.fr/simbad/sim-id?Ident=Epsilon+Pegasi",
    ],
    notes:
      "Enif (ε Peg, Epsilon Pegasi) — slow irregular variable (LC type); magnitude varies 2.37–2.45 (rarely to 3.5). Massive red supergiant near end of life; shows overabundance of Sr and Ba.",
  },
  {
    name: "Scheat",
    constellation: "Pegasus",
    visibility: "Northern",
    mag: 2.42,
    distance: 196,
    lum: 1644,
    temp: 3606,
    radius: 109,
    mass: 1.7,
    age: 4.5,
    spectral: "M2.5 II-III",
    starType: "Red giant",
    exo: false,
    exoCount: 0,
    uncertainty: [4],
    sources: [
      "https://en.wikipedia.org/wiki/Beta_Pegasi",
      "http://simbad.u-strasbg.fr/simbad/sim-id?Ident=Beta+Pegasi",
      "http://stars.astro.illinois.edu/sow/bright.html",
    ],
    notes:
      "Scheat (β Peg, Beta Pegasi) — semi-regular variable; magnitude varies 2.31–2.74 with period 43.3 days. Cool red giant on asymptotic giant branch (AGB); losing mass at ~10⁻⁸ M☉/yr creating expanding shell. Forms upper right corner of Great Square of Pegasus. Age estimated from AGB evolutionary models.",
  },
  {
    name: "Sabik",
    constellation: "Ophiuchus",
    visibility: "Southern",
    mag: 2.43,
    distance: 88,
    lum: 56,
    temp: 9000,
    radius: 2.5,
    mass: 2.25,
    age: 0.5,
    spectral: "A2 V",
    numStars: 2,
    starType: "Main sequence",
    exo: false,
    exoCount: 0,
    components: [
      { name: "Sabik A", spec: "A2V" },
      { name: "Sabik B", spec: "A2V" },
    ],
    sources: [
      "https://en.wikipedia.org/wiki/Eta_Ophiuchi",
      "http://simbad.u-strasbg.fr/simbad/sim-id?Ident=Eta+Ophiuchi",
      "http://stars.astro.illinois.edu/sow/bright.html",
    ],
    notes:
      "Sabik (η Oph, Eta Ophiuchi) — binary with 87.8 year orbit; highly eccentric (e=0.931), periastron occurred 2024. Both A2V main-sequence stars fusing hydrogen. Individual magnitudes +3.05 and +3.27.",
  },
  {
    name: "Aludra",
    constellation: "Canis Major",
    visibility: "Southern",
    mag: 2.45,
    distance: 2000,
    lum: 163800,
    temp: 15800,
    radius: 54,
    mass: 9.5,
    age: 0.0083,
    spectral: "B5 Ia",
    starType: "Blue supergiant",
    exo: false,
    exoCount: 0,
    uncertainty: [1, 4],
    sources: [
      "https://en.wikipedia.org/wiki/Eta_Canis_Majoris",
      "http://simbad.u-strasbg.fr/simbad/sim-id?Ident=Eta+Canis+Majoris",
      "http://stars.astro.illinois.edu/sow/bright.html",
    ],
    notes:
      "Aludra (η CMa, Eta Canis Majoris) — Alpha Cygni-type variable; magnitude 2.38–2.48 with 4.7-day period. Likely post-red supergiant near end of life; formed with 22 M☉, now ~9.5 M☉ due to mass loss. Strong stellar wind. Distance uncertain (values 2000-3200 ly).",
  },
  {
    name: "Alderamin",
    constellation: "Cepheus",
    visibility: "Northern",
    mag: 2.46,
    distance: 49,
    lum: 17,
    temp: 8440,
    radius: 2.82,
    mass: 2.0,
    age: 0.82,
    spectral: "A7 IV-V",
    starType: "Subgiant",
    exo: false,
    exoCount: 0,
    sources: [
      "https://en.wikipedia.org/wiki/Alpha_Cephei",
      "http://simbad.u-strasbg.fr/simbad/sim-id?Ident=Alpha+Cephei",
      "http://stars.astro.illinois.edu/sow/bright.html",
    ],
    notes:
      "Alderamin (α Cep, Alpha Cephei) — rapid rotator (v sin i = 246 km/s); rotation period <12 hours. Oblate shape: equatorial radius 2.82 R☉, polar 2.18 R☉; temperature varies 8440K (poles) to 7600K (equator). Will be North Pole Star around 7500 AD. Delta Scuti variable. X-ray emission despite rapid rotation.",
  },
  {
    name: "Gamma Cassiopeiae",
    constellation: "Cassiopeia",
    visibility: "Northern",
    mag: 2.47,
    distance: 550,
    lum: 19000,
    temp: 25000,
    radius: 10.9,
    mass: 17,
    age: 0.008,
    spectral: "B0.5 IVe",
    starType: "Subgiant",
    exo: false,
    exoCount: 0,
    uncertainty: [4],
    sources: [
      "https://en.wikipedia.org/wiki/Gamma_Cassiopeiae",
      "http://simbad.u-strasbg.fr/simbad/sim-id?Ident=Gamma+Cassiopeiae",
      "http://stars.astro.illinois.edu/sow/bright.html",
    ],
    notes:
      "Gamma Cassiopeiae (γ Cas) — prototype Gamma Cas variable; first Be star ever identified (1866). Eruptive variable: brightened to >mag 2.0 in 1930s, dropped to 3.4, now ~2.2. Rapid rotator (450 km/s); oblate with equatorial bulge creating decretion disk. Strong X-ray emitter (~10³³ erg/s). Center of 'W' asterism. Likely 8-star system including companion HD 5408.",
  },
  {
    name: "Markab",
    constellation: "Pegasus",
    visibility: "Northern",
    mag: 2.49,
    distance: 133,
    lum: 165,
    temp: 10100,
    radius: 4.62,
    mass: 3.5,
    age: 0.2,
    spectral: "B9 V",
    starType: "Subgiant",
    exo: false,
    exoCount: 0,
    sources: [
      "https://en.wikipedia.org/wiki/Alpha_Pegasi",
      "http://simbad.u-strasbg.fr/simbad/sim-id?Ident=Alpha+Pegasi",
      "http://stars.astro.illinois.edu/sow/bright.html",
    ],
    notes:
      "Markab (α Peg, Alpha Pegasi) — A0 IV or B9V classification; subgiant evolving off main sequence. Rapid rotator (v sin i = 130 km/s). Known for being 'normal' with no spectral peculiarities. Forms lower right corner of Great Square of Pegasus.",
  },
  {
    name: "Gienah (Epsilon Cygni)",
    constellation: "Cygnus",
    visibility: "Northern",
    mag: 2.48,
    distance: 73,
    lum: 56,
    temp: 4699,
    radius: 11.13,
    mass: 1.1,
    age: 9.62,
    spectral: "K0 III",
    numStars: 2,
    starType: "Giant",
    exo: false,
    exoCount: 0,
    components: [
      { name: "Gienah A", spec: "K0 III" },
      { name: "Gienah B", spec: "Unknown" },
    ],
    sources: [
      "https://en.wikipedia.org/wiki/Epsilon_Cygni",
      "http://simbad.u-strasbg.fr/simbad/sim-id?Ident=Epsilon+Cygni",
      "http://stars.astro.illinois.edu/sow/bright.html",
    ],
    notes:
      "Gienah/Aljanah (ε Cyg, Epsilon Cygni) — single-lined spectroscopic binary; 53-year orbit, highly eccentric (e=0.93). K0 III giant + unseen companion (≥0.265 M☉). Horizontal branch star. Spectrum served as MK classification anchor since 1943. Located 3° north of Veil Nebula.",
  },
  {
    name: "Acrab",
    constellation: "Scorpius",
    visibility: "Southern",
    mag: 2.5,
    distance: 400,
    lum: 31600,
    temp: 28000,
    radius: 6.3,
    mass: 15.0,
    age: 0.0063,
    spectral: "B1 V",
    numStars: 6,
    starType: "Main sequence",
    exo: false,
    exoCount: 0,
    components: [
      { name: "Acrab Aa", spec: "B0.5IV-V", visualSize: 1.2 },
      { name: "Acrab Ab", spec: "B1.5V", visualSize: 1.0 },
      { name: "Acrab C", spec: "B2V", visualSize: 0.8 },
      { name: "Acrab E", spec: "HgMn", visualSize: 0.6 },
    ],
    uncertainty: [2],
    sources: [
      "https://en.wikipedia.org/wiki/Beta_Scorpii",
      "http://simbad.u-strasbg.fr/simbad/sim-id?Ident=Beta+Scorpii",
      "http://stars.astro.illinois.edu/sow/bright.html",
    ],
    notes:
      "Acrab/Graffias (β Sco, Beta Scorpii) — hierarchical sextuple star system. β¹ Sco contains Aa+Ab binary (6.82d period) + B companion (610y period). β² Sco contains C+E binary (39y; E is HgMn chemically peculiar). System age ~6 Myr, member of Upper Scorpius association. Separation β¹-β² is 13.5 arcsec.",
  },
  {
    name: "Markeb",
    constellation: "Vela",
    visibility: "Southern",
    mag: 2.5,
    distance: 570,
    lum: 13200,
    temp: 18200,
    radius: 11.6,
    mass: 9.44,
    age: 0.0157,
    spectral: "B2 IV",
    numStars: 2,
    starType: "Subgiant",
    exo: false,
    exoCount: 0,
    components: [
      { name: "A", spec: "B2 IV", visualSize: 1 },
      { name: "B", spec: "~B", visualSize: 0.4 },
    ],
    sources: [
      "https://en.wikipedia.org/wiki/Kappa_Velorum",
      "http://simbad.u-strasbg.fr/simbad/sim-id?Ident=Kappa+Velorum",
      "http://stars.astro.illinois.edu/sow/bright.html",
    ],
    notes:
      "Markeb (κ Vel, Kappa Velorum) — spectroscopic binary; 116.65-day orbit with e=0.19. B2 IV subgiant exhausting core hydrogen. Will be closest bright star to south celestial pole around 9000 AD. Shows variable interstellar absorption features.",
  },
  {
    name: "Menkar",
    constellation: "Cetus",
    visibility: "Both",
    mag: 2.54,
    distance: 249,
    lum: 1764,
    temp: 3738,
    radius: 100.2,
    mass: 2.3,
    age: 6.0,
    spectral: "M1.5 IIIa",
    starType: "Giant",
    exo: false,
    exoCount: 0,
    sources: [
      "https://en.wikipedia.org/wiki/Alpha_Ceti",
      "http://simbad.u-strasbg.fr/simbad/sim-id?Ident=Alpha+Ceti",
      "http://stars.astro.illinois.edu/sow/bright.html",
    ],
    notes:
      "Menkar (α Cet, Alpha Ceti) — red giant on asymptotic giant branch (AGB); has exhausted both core hydrogen and helium. M1.5 IIIa classification; cool luminous star (T~3738K, L~1764 L☉). Evolved from 2.3 M☉ main-sequence star. Will likely become Mira-like variable before shedding outer layers as planetary nebula. Second brightest in Cetus after Beta Ceti (Diphda).",
  },
  {
    name: "Zeta Centauri",
    constellation: "Centaurus",
    visibility: "Southern",
    mag: 2.55,
    distance: 382,
    lum: 8500,
    temp: 23561,
    radius: 5.8,
    mass: 7.8,
    age: 0.0398,
    spectral: "B2.5 IV",
    starType: "Subgiant",
    numStars: 2,
    exo: false,
    exoCount: 0,
    sources: [
      "https://en.wikipedia.org/wiki/Zeta_Centauri",
      "http://simbad.u-strasbg.fr/simbad/sim-id?Ident=Zeta+Centauri",
      "http://stars.astro.illinois.edu/sow/bright.html",
    ],
    notes:
      "Zeta Centauri (ζ Cen, also named Leepwal) — spectroscopic binary in Centaurus. B2.5 IV subgiant; primary has ~7.8 M☉ and ~5.8 R☉. Rapid rotator (v sin i = 235 km/s). Binary orbit: P=8.024 days, e=0.5, separation ~0.0014 arcsec. Age ~40 Myr (young system). Hot blue-white star with T~23,561K. Rank 94 in Jim Kaler's brightest 172 stars.",
  },
  {
    name: "Zosma",
    constellation: "Leo",
    visibility: "Northern",
    mag: 2.56,
    distance: 58.4,
    lum: 15.5,
    temp: 8296,
    radius: 2.14,
    mass: 2.2,
    age: 0.6,
    spectral: "A4 V",
    starType: "Main sequence",
    exo: false,
    exoCount: 0,
    sources: [
      "https://en.wikipedia.org/wiki/Delta_Leonis",
      "http://simbad.u-strasbg.fr/simbad/sim-id?Ident=Delta+Leonis",
      "http://stars.astro.illinois.edu/sow/bright.html",
    ],
    notes:
      "Zosma (δ Leo, Delta Leonis) — A4 V main-sequence star; rapidly rotating (v sin i = 180 km/s) creating oblate shape with polar radius ~84% of equatorial radius. Member of Ursa Major Moving Group (age ~500 Myr). Name means 'girdle' in ancient Greek, referring to position on lion's hip. Will evolve into orange/red giant in ~600 Myr.",
  },
  {
    name: "Arneb",
    constellation: "Lepus",
    visibility: "Southern",
    mag: 2.58,
    distance: 2200,
    lum: 27000,
    temp: 7253,
    radius: 74,
    mass: 13,
    age: 0.013,
    spectral: "F0 Ib",
    starType: "Supergiant",
    exo: false,
    exoCount: 0,
    sources: [
      "https://en.wikipedia.org/wiki/Alpha_Leporis",
      "http://simbad.u-strasbg.fr/simbad/sim-id?Ident=Alpha+Leporis",
      "http://stars.astro.illinois.edu/sow/bright.html",
    ],
    notes:
      "Arneb (α Lep, Alpha Leporis) — yellow-white supergiant (F0 Ib); in 'blue loop' phase after red supergiant stage, now contracting and heating. Massive star (12-13 M☉) in late evolutionary stages; age ~13 Myr. Name from Arabic 'arnab' meaning 'hare' (Lepus is Latin for hare). Weak magnetic field detected. Brightest star in Lepus.",
  },
  {
    name: "Izar",
    constellation: "Boötes",
    visibility: "Northern",
    mag: 2.59,
    distance: 236,
    lum: 652.5,
    temp: 4755,
    radius: 37.61,
    mass: 4.6,
    age: 0.037,
    spectral: "K0 II-III",
    numStars: 2,
    starType: "Giant",
    exo: false,
    exoCount: 0,
    components: [
      { name: "Izar A", spec: "K0 II-III", visualSize: 1.2 },
      { name: "Izar B", spec: "A2 V", visualSize: 0.6 },
    ],
    sources: [
      "https://en.wikipedia.org/wiki/Epsilon_Boötis",
      "http://simbad.u-strasbg.fr/simbad/sim-id?Ident=Epsilon+Boötis",
      "http://stars.astro.illinois.edu/sow/bright.html",
    ],
    notes:
      "Izar (ε Boo, Epsilon Boötis) — beautiful binary system; primary K0 II-III orange giant (mag 2.45) + companion A2 V white main-sequence star (mag 4.8). Also called 'Pulcherrima' (Latin: 'loveliest') by F.G.W. Struve. Separation 2.9 arcsec, period >1000 years. Challenging target for small telescopes; requires 76mm+ aperture. Primary on red giant branch with 4.6 M☉.",
  },
  {
    name: "Iota Aurigae (Hassaleh)",
    constellation: "Auriga",
    visibility: "Northern",
    mag: 2.69,
    distance: 450,
    lum: 3897,
    temp: 3970,
    radius: 126,
    mass: 7.1,
    age: 0.0398,
    spectral: "K3 II-III",
    starType: "Giant",
    exo: false,
    exoCount: 0,
    sources: [
      "https://en.wikipedia.org/wiki/Iota_Aurigae",
      "http://simbad.u-strasbg.fr/simbad/sim-id?Ident=Iota+Aurigae",
      "http://stars.astro.illinois.edu/sow/bright.html",
    ],
    notes:
      "Hassaleh (ι Aur) — hybrid K3 II-III giant; classification between bright giant and giant. Suspected variable star; X-ray emitter. Unconfirmed reports of possible brown dwarf companions.",
  },
  {
    name: "Kappa Scorpii",
    constellation: "Scorpius",
    visibility: "Southern",
    mag: 2.4,
    distance: 480,
    lum: 7200,
    temp: 24000,
    radius: 6.5,
    mass: 11,
    age: 0.0151,
    spectral: "B1.5 III",
    numStars: 2,
    starType: "Giant",
    exo: false,
    exoCount: 0,
    components: [
      { name: "A", spec: "B1.5 III", visualSize: 1 },
      { name: "B", spec: "B2 III", visualSize: 0.9 },
    ],
    sources: [
      "https://en.wikipedia.org/wiki/Kappa_Scorpii",
      "http://simbad.u-strasbg.fr/simbad/sim-id?Ident=Kappa+Scorpii",
      "http://stars.astro.illinois.edu/sow/bright.html",
    ],
    notes:
      "Girtab (κ Sco) — Beta Cephei variable with 4.8-hour period; binary system with 195-day orbit (e=0.5). Primary 11 M☉ (7 R☉), secondary 10 M☉ (6 R☉). Age ~15 Myr.",
  },
  {
    name: "Delta Centauri (Ma Wei)",
    constellation: "Centaurus",
    visibility: "Southern",
    mag: 2.58,
    distance: 410,
    lum: 5129,
    temp: 22150,
    radius: 8.18,
    mass: 8.7,
    age: 0.0215,
    spectral: "B2Vne",
    starType: "Main sequence",
    exo: false,
    exoCount: 0,
    sources: [
      "https://en.wikipedia.org/wiki/Delta_Centauri",
      "http://simbad.u-strasbg.fr/simbad/sim-id?Ident=Delta+Centauri",
      "http://stars.astro.illinois.edu/sow/bright.html",
    ],
    notes:
      "Ma Wei (δ Cen) — Gamma Cassiopeiae variable (mag 2.51-2.65); B2Vne shell star; rapid rotator creating circumstellar disk (v sin i = 12-35 km/s). Possible binary. Lower Centaurus-Crux association member.",
  },
  {
    name: "Lambda Scorpii (Shaula)",
    constellation: "Scorpius",
    visibility: "Southern",
    mag: 1.63,
    distance: 570,
    lum: 36300,
    temp: 25000,
    radius: 8.8,
    mass: 14.5,
    age: 0.0115,
    spectral: "B1.5IV + B2IV",
    numStars: 3,
    starType: "Subgiant",
    exo: false,
    exoCount: 0,
    components: [
      { name: "Shaula A", spec: "B1.5IV", visualSize: 1.3 },
      { name: "Shaula B", spec: "B2IV", visualSize: 1.1 },
      { name: "Shaula C", spec: "pre-MS", visualSize: 0.5 },
    ],
    sources: [
      "https://en.wikipedia.org/wiki/Lambda_Scorpii",
      "http://simbad.u-strasbg.fr/simbad/sim-id?Ident=Lambda+Scorpii",
      "http://stars.astro.illinois.edu/sow/bright.html",
    ],
    notes:
      "Shaula (λ Sco) — triple system with B1.5IV + B2IV subgiants (14.5/10.6 M☉) + pre-main-sequence companion (2.0 M☉). Beta Cephei variable + Algol-type eclipsing system. Age 10-13 Myr.",
  },
  {
    name: "Alpha Lupi",
    constellation: "Lupus",
    visibility: "Southern",
    mag: 2.3,
    distance: 460,
    lum: 18200,
    temp: 24550,
    radius: 7.0,
    mass: 10.1,
    age: 0.018,
    spectral: "B1.5 III",
    starType: "Giant",
    exo: false,
    exoCount: 0,
    sources: [
      "https://en.wikipedia.org/wiki/Alpha_Lupi",
      "http://simbad.u-strasbg.fr/simbad/sim-id?Ident=Alpha+Lupi",
      "http://stars.astro.illinois.edu/sow/bright.html",
    ],
    notes:
      "Men (α Lup) — B1.5 III giant; Beta Cephei variable with 0.29585-day period. Upper Centaurus-Lupus OB association member. Age 16-20 Myr.",
  },
  {
    name: "Beta Arietis (Sheratan)",
    constellation: "Aries",
    visibility: "Northern",
    mag: 2.655,
    distance: 58.4,
    lum: 20.9,
    temp: 8100,
    radius: 2.3,
    mass: 2.067,
    age: 0.63,
    spectral: "A3V + G2V",
    numStars: 2,
    starType: "Main sequence",
    exo: false,
    exoCount: 0,
    sources: [
      "https://en.wikipedia.org/wiki/Beta_Arietis",
      "http://simbad.u-strasbg.fr/simbad/sim-id?Ident=Beta+Arietis",
      "http://stars.astro.illinois.edu/sow/bright.html",
    ],
    notes:
      "Sheratan (β Ari) — binary system with 107-day eccentric orbit (e=0.903); A3V primary (2.067 M☉, 20.9 L☉) + G2V secondary (1.058 M☉, 1.29 L☉). Age 630 Myr.",
  },
  {
    name: "Alpha Coronae Borealis (Alphecca)",
    constellation: "Corona Borealis",
    visibility: "Northern",
    mag: 2.24,
    distance: 75,
    lum: 74,
    temp: 9700,
    radius: 3.0,
    mass: 2.581,
    age: 0.4,
    spectral: "A0V + G5V",
    numStars: 2,
    starType: "Main sequence",
    exo: false,
    exoCount: 0,
    sources: [
      "https://en.wikipedia.org/wiki/Alpha_Coronae_Borealis",
      "http://simbad.u-strasbg.fr/simbad/sim-id?Ident=Alpha+Coronae+Borealis",
      "http://stars.astro.illinois.edu/sow/bright.html",
    ],
    notes:
      "Alphecca/Gemma (α CrB) — eclipsing binary (A0V + G5V) with 17.36-day eccentric orbit. Primary 2.581 M☉ (74 L☉), secondary 0.922 M☉ (0.83 L☉). Ursa Major Moving Group member. Age 400 Myr.",
  },
];

// Expose `stars` globally (already global via const); kept for clarity.
// If you prefer a module pattern, we can switch to exporting the array and
// update the HTML to load as a module (<script type="module">).
